### ISSUE TITLE
Dynamic routing triggers dependencies updated, reloading Page...

### ISSUE THREAD

**Issue by yinfoyuan** [antfu/unplugin-vue-components#108]
https://codesandbox.io/s/young-haze-23h3u

I need to override the less variable

How can it be avoided

<img width="527" alt="DDD" src="https://user-images.githubusercontent.com/35027364/126727475-aad03919-5aa2-4578-bc22-15a76ebd30eb.png">
<img width="960" alt="ant" src="https://user-images.githubusercontent.com/35027364/126727481-31b1b4cb-9c98-4792-b923-1f49fae1d86e.png">

**Comment by antfu** [comment]
https://github.com/antfu/vite-plugin-optimize-persist
