### ISSUE TITLE
customComponentResolvers for @heroicons/vue

### ISSUE THREAD

**Issue by eyeruleall** [antfu/unplugin-vue-components#109]
I wanted to share and ask for feedback for my custom resolver for @heroicons/vue. 

Since @heroicons/vue exports from a subdirectory (@heroicons/vue/outline or @heroicons/vue/solid depending on if you want a solid or outlined icon), I simply appended this info to the import name (calling `<KeyIconOutline />` or `<KeyIconSolid />`, for instance). 

```
(name) => {
  if (name.endsWith("IconOutline")) {
    return {
      importName: name.substring(0, name.indexOf("Outline")),
      path: `@heroicons/vue/outline`,
    };
  } else if (name.endsWith("IconSolid")) {
    return {
      importName: name.substring(0, name.indexOf("Solid")),
      path: `@heroicons/vue/solid`,
    };
  }
},
```

Does anyone have any better ideas for how to handle specifying which version of the icon to import?

**Comment by antfu** [comment]
I would use https://github.com/antfu/vite-plugin-icons with https://icones.js.org/collection/heroicons-outline
