### ISSUE TITLE
Dynamic component support

### ISSUE THREAD

**Issue by calvin-cg** [antfu/unplugin-vue-components#11]
Is this plugin support dynamic components? Such as using `<component :is="" />`
I tried to use this plugin using dynamic components, but it's not rendering.

Example:
```html
<!-- rendered to <mybutton /> -->
<component :is="'myButton'" />

<!-- correctly rendered -->
<myButton>
```

**Comment by antfu** [comment]
Any reason for this tho? I think dynamic component is mostly used by components that you already have reference to instead of a plain string.

**Comment by Septias** [comment]
I would like it too

**Comment by sampullman** [comment]
As far as I can tell, this is difficult to solve perfectly with a Vite plugin. One alternative, assuming you know the list of components ahead of time, could be to resolve them from a special property defined by `vite-plugin-components`, for example:
```
<component :is="child.breed" :components="[Child1, Child2, Child3]" />
```
It adds some burden to the transform regex, which might not be acceptable for large projects.

Another option could be to automatically resolve missing components from `export default = { components: [Child1, Child2, Child3] };`, but that doesn't really save a ton of dev effort and probably has a lot of edge cases.

**Comment by praburangki** [comment]
Another example use case:

We are trying to build a form generator component. Inside the form component it can render either an input, select, checkbox etc. By reading the JSON schema we want to render each component that are defined in each property.

**Comment by antfu** [comment]
> Any reason for this tho? I think dynamic component is mostly used by components that you already have reference to instead of a plain string.

To make myself clear:

```html
<script setup>
import A from './A.vue'
import B from './B.vue'

const name = ref('a')
const Comp = name.value === 'a' ? A : B
</script>

<template>
  <component :is="Comp" />
</template>
```

Please note that the Vite plugin is a build-time process and would not be able to get the value of variables in the runtime. For dynamic usages, I'd suggest you either use global/component-level registration, or `<script setup>` (which I think is concise enough).

**Comment by husayt** [comment]
@antfu This would be very useful along with i18n. Let's assume we have markdown files "hello.en.md" and "hello.jp.md". You only want to use the one which matches current locale e.g.
```
<script setup>
const { locale } = useI18n()
const pagename=`hello.${locale}`
</script>

<template>
  <component :is="pageName" />
</template>
```

Or maybe there is an existing pattern and I am missing something obvious?

**Comment by Jogai** [comment]
> Any reason for this tho? I think dynamic component is mostly used by components that you already have reference to instead of a plain string.

In our case (and the cases from @praburangki and @husayt) we really just reference a string. We made it work for development, but it still breaks during a production build. It would help us a lot if this was possible. Its obvious that variables are not available during build-time, but maybe a there could be an option to include some whitelisted folders/components?

In our case its a wizard component that can load 1-n steps, depending on what type of wizard we want to show. Here is our structure and our working component:

```html
Our components structure:

│   Wizard.vue
│
├───SomeWizardSteps
│       SomeWizardStep-1.vue
│       SomeWizardStep-2.vue
│       SomeWizardStep-3.vue
│
└───SomeOtherWizardSteps
        SomeOtherWizardStep-1.vue
        SomeOtherWizardStep-2.vue
        SomeOtherWizardStep-3.vue
        SomeOtherWizardStep-4.vue
        SomeOtherWizardStep-5.vue


//Wizard.vue

<template>
  <KeepAlive>
    <Suspense>
      <component :is="stepComponent(step)">
        <div>
          <button class="btn btn-labeled-right no-label-bg btn-success font-weight-semibold mr-5" @click="next">
            Ga verder
            <span class="btn-label"> <i class="far fa-chevron-right"></i> </span>
          </div>
        </template>
      </component>
    </Suspense>
  </KeepAlive>
</template>

<script lang="ts" setup>
const props = defineProps<{
  stepMaximum: number;
  stepPrefix: "";
}>();

let step = $ref(1);

function next() {
  if (step < props.stepMaximum) {
    step++;
  }
}
const stepComponent = (x: number) => defineAsyncComponent(() => import(`./${props.stepPrefix}Step-${x}.vue`));
</script>

**Comment by jackhuynh95** [comment]
> > Any reason for this tho? I think dynamic component is mostly used by components that you already have reference to instead of a plain string.
> 
> In our case (and the cases from @praburangki and @husayt) we really just reference a string. We made it work for development, but it still breaks during a production build. It would help us a lot if this was possible. Its obvious that variables are not available during build-time, but maybe a there could be an option to include some whitelisted folders/components?
> 
> In our case its a wizard component that can load 1-n steps, depending on what type of wizard we want to show. Here is our structure and our working component:
> 
> ```
> Our components structure:
> 
> │   Wizard.vue
> │
> ├───SomeWizardSteps
> │       SomeWizardStep-1.vue
> │       SomeWizardStep-2.vue
> │       SomeWizardStep-3.vue
> │
> └───SomeOtherWizardSteps
>         SomeOtherWizardStep-1.vue
>         SomeOtherWizardStep-2.vue
>         SomeOtherWizardStep-3.vue
>         SomeOtherWizardStep-4.vue
>         SomeOtherWizardStep-5.vue
> 
> 
> //Wizard.vue
> 
> <template>
>   <KeepAlive>
>     <Suspense>
>       <component :is="stepComponent(step)">
>         <div>
>           <button class="btn btn-labeled-right no-label-bg btn-success font-weight-semibold mr-5" @click="next">
>             Ga verder
>             <span class="btn-label"> <i class="far fa-chevron-right"></i> </span>
>           </div>
>         </template>
>       </component>
>     </Suspense>
>   </KeepAlive>
> </template>
> 
> <script lang="ts" setup>
> const props = defineProps<{
>   stepMaximum: number;
>   stepPrefix: "";
> }>();
> 
> let step = $ref(1);
> 
> function next() {
>   if (step < props.stepMaximum) {
>     step++;
>   }
> }
> const stepComponent = (x: number) => defineAsyncComponent(() => import(`./${props.stepPrefix}Step-${x}.vue`));
> </script>
> ```



> > Any reason for this tho? I think dynamic component is mostly used by components that you already have reference to instead of a plain string.
> 
> In our case (and the cases from @praburangki and @husayt) we really just reference a string. We made it work for development, but it still breaks during a production build. It would help us a lot if this was possible. Its obvious that variables are not available during build-time, but maybe a there could be an option to include some whitelisted folders/components?
> 
> In our case its a wizard component that can load 1-n steps, depending on what type of wizard we want to show. Here is our structure and our working component:
> 
> ```
> Our components structure:
> 
> │   Wizard.vue
> │
> ├───SomeWizardSteps
> │       SomeWizardStep-1.vue
> │       SomeWizardStep-2.vue
> │       SomeWizardStep-3.vue
> │
> └───SomeOtherWizardSteps
>         SomeOtherWizardStep-1.vue
>         SomeOtherWizardStep-2.vue
>         SomeOtherWizardStep-3.vue
>         SomeOtherWizardStep-4.vue
>         SomeOtherWizardStep-5.vue
> 
> 
> //Wizard.vue
> 
> <template>
>   <KeepAlive>
>     <Suspense>
>       <component :is="stepComponent(step)">
>         <div>
>           <button class="btn btn-labeled-right no-label-bg btn-success font-weight-semibold mr-5" @click="next">
>             Ga verder
>             <span class="btn-label"> <i class="far fa-chevron-right"></i> </span>
>           </div>
>         </template>
>       </component>
>     </Suspense>
>   </KeepAlive>
> </template>
> 
> <script lang="ts" setup>
> const props = defineProps<{
>   stepMaximum: number;
>   stepPrefix: "";
> }>();
> 
> let step = $ref(1);
> 
> function next() {
>   if (step < props.stepMaximum) {
>     step++;
>   }
> }
> const stepComponent = (x: number) => defineAsyncComponent(() => import(`./${props.stepPrefix}Step-${x}.vue`));
> </script>
> ```

it work well, thank so much

**Comment by jackhuynh95** [comment]
Hey @Jogai about your solution  => it work well, thanks so much 

```
return defineAsyncComponent(
    () => import(`@/components/main/${component}.vue`),
 )
```

**Comment by gyt95** [comment]
After searching for a long time, I only found [antfu's answer](https://github.com/antfu/unplugin-auto-import/issues/208#issuecomment-1172070913) in a certain issue. I think this is a better answer. Indeed, you can only explicitly import, alas.
