### ISSUE TITLE
Missing style when import some components from ant-design-vue

### ISSUE THREAD

**Issue by weeksun23** [antfu/unplugin-vue-components#114]
I already set AntDesignVueResolver in vite.config.ts
```
import { Form, Input, Button, Row, Col, message, notification } from "ant-design-vue";
```
Above code, only message and notification component have not style, other components are normal;
```
message.info('test');
notification.info({
  description: "test",
  message: "content",
});
```
Above code can run,but just missing style.Why? Is my configuration incorrect?

**Comment by weeksun23** [comment]
Must manual import
```
import "ant-design-vue/lib/message/style/index.css";
import "ant-design-vue/lib/notification/style/index.css";
```

**Comment by nabaonan** [comment]
> Must manual import
> 
> ```
> import "ant-design-vue/lib/message/style/index.css";
> import "ant-design-vue/lib/notification/style/index.css";
> ```

 vite-plugin-style-import  is useful in javascript import ,i think this plugin design for template

**Comment by nabaonan** [comment]
@antfu has any plan support load compnent on demand in js?

**Comment by zzlit** [comment]
@antfu `unplugin-vue-components` v0.14.6 same problem in vant,
```
// vite.config.ts
import Components from 'unplugin-vue-components/vite';
import { VantResolver } from 'unplugin-vue-components/resolvers';

plugins: [
  Components({
    resolvers: [VantResolver()]
  })
]
```
```
// page
import { Toast } from 'vant';

Toast('xxxx'); // miss toast style
```

**Comment by antfu** [comment]
> @antfu has any plan support load compnent on demand in js?

That would probably be out-of-scope of this project, doesn't `vite-plugin-style-import` fit what you need here?

**Comment by nabaonan** [comment]
> > @antfu has any plan support load compnent on demand in js?
> 
> That would probably be out-of-scope of this project, doesn't `vite-plugin-style-import` fit what you need here?

Got it ,`vite-plugin-style-import` is fit for me to load on demand in js.
