### ISSUE TITLE
How to avoid modifying global styles when importing styles for components?

### ISSUE THREAD

**Issue by knozharov** [antfu/unplugin-vue-components#120]
The plugin does a great job of importing components and their styles on demand.

However, there are libraries such as `ant-design-vue` which include global reset styles alongside the component-scoped ones. As this impacts the overall style of an app, it should be somehow made configurable.

Ant Design have given instructions how to avoid modifying global styles by scoping via using webpack [here](https://2x.antdv.com/docs/vue/customize-theme) (section `Configure webpack to load an alternale less file and scope global styles`).

I have been trying to find a solution for a Vite setup but haven’t succeeded yet.
The options available for ViteComponents and the resolvers do not cover scoping the vendor-specific styles.
I looked at the `vite-plugin-style-import` plugin but it doesn’t seem to help either.
The Vite  CSS preprocessor configuration also doesn’t cover such a scenario.

I have been thinking about making a Rollup plugin which loads a .less file such as the one in the `ant-design-vue` example, when a file such as `node_modules/ant-design-vue/es/style/index.less` or `node_modules/ant-design-vue/lib/style/index.less` is being imported.

Could you advise how scoping of vendor-specific global styles can be done?
Can it somehow be achieved via the `vite-plugin-components` plugin?

Thank you in advance for your cooperation.

**Comment by antfu** [comment]
I think we are already handle them on-demand, https://github.com/antfu/vite-plugin-components/pull/81

/cc @nabaonan

**Comment by knozharov** [comment]
Thank you for your reply.

Yes, loading the `ant-design-vue` component styles on-demand works perfectly.

The problem is related to **global** styles and it may be specific to `ant-design-vue`: together with the component styles they also import unscoped global styles which interfere with the app’s layout.

The guys from Ant Design have provided a webpack-based solution which helps scope the **global** styles (see the link in my first post). However, I haven’t been able to do so with Vite. 

I was hoping that `vite-plugin-components` can add scope to the **global** styles that get imported alongside the vendor-specific components but it seems that such functionality is missing.

**Comment by antfu** [comment]
Maybe some postcss plugin would help?

**Comment by knozharov** [comment]
Sorry for not responding, just got carried away with other tasks in the meantime.

The context is that importing a component-specific style from the `ant-design-vue` library also drags with itself global styles which interfere with any existing ones. Ant Design have come up with a solution for webpack - a plug-in which detects the import of global styles and loads them with a prefix, e.g. #antd. I have been trying to find a similar solution for the Vite bundler, but still haven't come across an existing one. Currently it seems that I'll need to implement a Rollup-based plug-in in order to achieve this functionality.

Anyways, thank you for your suggestions, I did go through all PostCSS plug-ins I could find as well as the `vite-plugin-style-import` plug-in, but didn't find the functionality I need.
