### ISSUE TITLE
Superfluous apostrophe in generated d.ts

### ISSUE THREAD

**Issue by peterbud** [antfu/unplugin-vue-components#134]
Thanks for this excellent tool!

I have noticed that since the renaming and migrating to 'unplugin-vue-components', the generated d.ts file has a syntax error, namely there is a **apostrophe** at the beginning of the comment line, surrounding the "// Read more" text:

```
declare module 'vue' {
  export interface GlobalComponents {
    '// Read more': https://github.com/vuejs/vue-next/pull/3399
...
  }
}
```

**Comment by antfu** [comment]
Can you upgrade to the least version, remove the dts file and try again? We fixed it recently already

**Comment by peterbud** [comment]
Oh, I was already on the latest release, just did not know that I have to delete the file itself. Now it's working, thanks!
