### ISSUE TITLE
Going to definition or recognizing html tags in WebStorm/Intellij

### ISSUE THREAD

**Issue by gabrielcraveiro** [antfu/unplugin-vue-components#135]
Hi, first I would like to thank you for the lib, been using for some weeks now and it really helps with the development flow.

I only have one issue, seeing prop definition or going to original component is not really that bad, but webstorm keeps warning me that the component is an "unknown html tag". Is there a way to recognize the components or even going to definition using the plugin?

Right now my vite.config is:

    ViteComponents({
      customComponentResolvers: [
        ElementUiResolver(),
        ViteIconsResolver({
          componentPrefix: "",
        }),
      ],
    }),

![warning image](https://i.imgur.com/ghoPRZs.png)

Thanks guys!

**Comment by gabrielcraveiro** [comment]
Was searching more info and found this blog post in intelijj forum, seems like a webstorm issue.

https://youtrack.jetbrains.com/issue/WEB-48239

**Comment by antfu** [comment]
Then please keep track on their issue tracker, thanks.

**Comment by acidjazz** [comment]
FYI Jetbrains has filed a separate issue for supporting this:

https://youtrack.jetbrains.com/issue/WEB-52214

Possible to leave this open until it's fixed @antfu  ?

**Comment by acidjazz** [comment]
Also if anyone wants a crack at this issue and can't wait, I've built something similar https://github.com/fumeapp/nuxt-storm
