### ISSUE TITLE
Cannot find module 'unplugin-vue-components/vite'

### ISSUE THREAD

**Issue by IvyLin737** [antfu/unplugin-vue-components#136]
vite.config.ts
import Components from 'unplugin-vue-components/vite';
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';

Components({
            dts: true, // enabled by default if `typescript` is installed
            resolvers:[
                AntDesignVueResolver()
            ],
            include: [/\.vue$/, /\.vue\?vue/, /\.md$/],
        })

error:
failed to load config from /usr/local/var/www/html/vue/bi.dq/vite.config.ts
error when starting dev server:
Error: Cannot find module 'unplugin-vue-components/vite'
Require stack:
- /usr/local/var/www/html/vue/bi.dq/vite.config.ts
- /usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js
- /usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/cli.js
- /usr/local/var/www/html/vue/bi.dq/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/local/var/www/html/vue/bi.dq/vite.config.ts:31:31)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:72082:20)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)

**Comment by IvyLin737** [comment]
tsconfig.json

**Comment by IvyLin737** [comment]
> vite.config.ts
> import Components from 'unplugin-vue-components/vite';
> import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';
> 
> Components({
> dts: true, // enabled by default if `typescript` is installed
> resolvers:[
> AntDesignVueResolver()
> ],
> include: [/.vue$/, /.vue?vue/, /.md$/],
> })

tsconfig.json
"exclude": [
    "node_modules","dist"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
> 
> error:
> failed to load config from /usr/local/var/www/html/vue/bi.dq/vite.config.ts
> error when starting dev server:
> Error: Cannot find module 'unplugin-vue-components/vite'
> Require stack:
> 
> * /usr/local/var/www/html/vue/bi.dq/vite.config.ts
> * /usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js
> * /usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/cli.js
> * /usr/local/var/www/html/vue/bi.dq/node_modules/vite/bin/vite.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:618:27)
>   at Module.require (internal/modules/cjs/loader.js:771:19)
>   at require (internal/modules/cjs/helpers.js:68:18)
>   at Object. (/usr/local/var/www/html/vue/bi.dq/vite.config.ts:31:31)
>   at Module._compile (internal/modules/cjs/loader.js:868:30)
>   at Object.require.extensions. [as .ts] (/usr/local/var/www/html/vue/bi.dq/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:72082:20)
>   at Module.load (internal/modules/cjs/loader.js:731:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:644:12)
>   at Module.require (internal/modules/cjs/loader.js:771:19)

**Comment by antfu** [comment]
What's your node version? Please use v14 or above.

**Comment by zjlovezj** [comment]
> What's your node version? Please use v14 or above.

I can confirm, using node v16 fix this error.
