### ISSUE TITLE
unplugin-vue-components vs unplugin-auto-import [question]

### ISSUE THREAD

**Issue by orenmizr** [antfu/unplugin-vue-components#139]
isn't the components tool a subset of auto import ? or does the auto import only does so for vue/react api ie useState

**Comment by antfu** [comment]
Vue components need registration and do not work like ES module import. `auto-import` is for APIs, and also React components since they use simple module imports for components.

See https://antfu.me/posts/journey-with-icons-continues for more details.

**Comment by orenmizr** [comment]
since then... i saw your vitesse repo... very impressive stuff 👏
