### ISSUE TITLE
vue2 + element-ui 按需加载没有生效。

### ISSUE THREAD

**Issue by huise513** [antfu/unplugin-vue-components#144]
sorry，my english is bad。
按照配置 vue2+element-ui，构建时并没按需加载剔除多余模块。
vue3+element-plus同样配置之后，是生效了的。
![image](https://user-images.githubusercontent.com/24875279/133733731-0539886e-3c76-4e72-843a-12dcfcd267bd.png)
![image](https://user-images.githubusercontent.com/24875279/133734071-e6538e87-92c7-4373-8b40-d52abe0b5930.png)
![image](https://user-images.githubusercontent.com/24875279/133733917-00baffc3-5b18-4a71-8f17-731bfb2d51a8.png)

**Comment by huise513** [comment]
> sorry，my english is bad。
> 按照配置 vue2+element-ui，构建时并没按需加载剔除多余模块。
> vue3+element-plus同样配置之后，是生效了的。
> ![image](https://user-images.githubusercontent.com/24875279/133733731-0539886e-3c76-4e72-843a-12dcfcd267bd.png)
> ![image](https://user-images.githubusercontent.com/24875279/133734071-e6538e87-92c7-4373-8b40-d52abe0b5930.png)
> ![image](https://user-images.githubusercontent.com/24875279/133733917-00baffc3-5b18-4a71-8f17-731bfb2d51a8

**Comment by huise513** [comment]
不好意思，我的问题，不需要再手动引入了。

**Comment by MaybeQHL** [comment]
我用的vant2.0也没用 3.0可以

**Comment by jackchoumine** [comment]
> sorry，my english is bad。 按照配置 vue2+element-ui，构建时并没按需加载剔除多余模块。 vue3+element-plus同样配置之后，是生效了的。 ![image](https://user-images.githubusercontent.com/24875279/133733731-0539886e-3c76-4e72-843a-12dcfcd267bd.png) ![image](https://user-images.githubusercontent.com/24875279/133734071-e6538e87-92c7-4373-8b40-d52abe0b5930.png) ![image](https://user-images.githubusercontent.com/24875279/133733917-00baffc3-5b18-4a71-8f17-731bfb2d51a8.png)

请问 vue2 中element -ui  如何配置按需加载的呢？

**Comment by huise513** [comment]
@jackchoumine 

> > sorry，my english is bad。 按照配置 vue2+element-ui，构建时并没按需加载剔除多余模块。 vue3+element-plus同样配置之后，是生效了的。 ![image](https://user-images.githubusercontent.com/24875279/133733731-0539886e-3c76-4e72-843a-12dcfcd267bd.png) ![image](https://user-images.githubusercontent.com/24875279/133734071-e6538e87-92c7-4373-8b40-d52abe0b5930.png) ![image](https://user-images.githubusercontent.com/24875279/133733917-00baffc3-5b18-4a71-8f17-731bfb2d51a8.png)
> 
> 请问 vue2 中element -ui 如何配置按需加载的呢？ @huise513

不需要再配置了，只需要在vite.config.js中配置了插件就好了，自动识别el-button这种标签的。
