### ISSUE TITLE
Configuration option to add semi colon / change quote of generated components.d.ts

### ISSUE THREAD

**Issue by coyotte508** [antfu/unplugin-vue-components#148]
Make `generateDeclaration` flexible (maybe have `options.dts` accept an object?)

Otherwise the file is constantly marked as changed if the linter / lint staged configuration changes the semi colon / quote setting during commit.

**Comment by Djaler** [comment]
I think you should exclude this file from linter config

**Comment by sxzz** [comment]
You should exclude dts file in Prettier or ESLint.
