### ISSUE TITLE
Error happens when use ElementPlusResolver And use directive

### ISSUE THREAD

**Issue by qc-z** [antfu/unplugin-vue-components#152]
## console
![image](https://user-images.githubusercontent.com/22362903/134790741-d53a9620-3ea2-4d2a-932b-337636dcd4c4.png)
## code
![image](https://user-images.githubusercontent.com/22362903/134790758-14353bd1-9402-440c-ada3-a48e03d901eb.png)
## vite.config.js
![image](https://user-images.githubusercontent.com/22362903/134790777-3b93052c-44c2-45d3-8c3a-c1b5a2d9a2a0.png)

**Comment by antfu** [comment]
This plugin does not auto-register directives. You will need to register yourself.
