### ISSUE TITLE
Option to import directives in UI resolver?

### ISSUE THREAD

**Issue by JohnCampionJr** [antfu/unplugin-vue-components#155]
Related to #152, I'm working on adding a few missing items to the PrimeVue resolver and I would love the ability to add a few directives that it uses.    I like that it can already import the CSS, it'd be great to have it handle the remaining directives for PrimeVue.

I can do a PR for the easier part of updating the resolver, but I'm not sure whether you even want any ability to add directives and if so, how to do that :)

```js
app.directive('tooltip', Tooltip)
app.directive('badge', BadgeDirective)
app.directive('ripple', Ripple)
```

**Comment by qc-z** [comment]
Thank you for your idea
