### ISSUE TITLE
Type display is not supported in JSX syntax

### ISSUE THREAD

**Issue by joker77877** [antfu/unplugin-vue-components#157]
![image](https://user-images.githubusercontent.com/62642184/134874339-8dc22ab6-c8a7-4ffd-bd37-bec385fca042.png)

![image](https://user-images.githubusercontent.com/62642184/134874382-43705d4e-1027-4c1d-984c-52b3404fac8f.png)

**Comment by antfu** [comment]
For tsx, use unplugin-auto-import

**Comment by joker77877** [comment]
Thank you!!

**Comment by joker77877** [comment]
How can I use AntDesignVueResolverin unplugin-auto-import?

**Comment by antfu** [comment]
Yes, the same resolvers optoons. But you will need to import the resolvers from this plugin

**Comment by joker77877** [comment]
Do you have an example? I introduced invalidity.
![image](https://user-images.githubusercontent.com/62642184/134888479-28614fa3-a604-44d1-a0a9-e2d9c91829ae.png)

**Comment by joker77877** [comment]
Please give me a configuration.
