### ISSUE TITLE
ant-design-vue 的message和Modal没有样式

### ISSUE THREAD

**Issue by losetime** [antfu/unplugin-vue-components#162]
plugins: [
    vue(),
    Components({
      resolvers: [
        AntDesignVueResolver({
          importStyle: 'less',
        })
      ],
    }),
  ]

使用message和Modal时没有样式， message和Modal的样式要单独引入吗？

**Comment by wanliyunyan** [comment]
vant 的 toast 也是没有样式，一直以为只有我自己遇到这个问题呢，结果遇到难兄难弟了

**Comment by nabaonan** [comment]
在template中引入也没有样式吗？ @losetime

**Comment by losetime** [comment]
> 在template中引入也没有样式吗？ @losetime 

目前我是在main文件中单独引入这两个组件的样式文件，可以解决

**Comment by losetime** [comment]
> vant 的 toast 也是没有样式，一直以为只有我自己遇到这个问题呢，结果遇到难兄难弟了

**Comment by liuzh1516** [comment]
我推测没有样式是因为没有在template中显式引入，比如<a-message>，而是通过代码方式调用的比如import { message } from 'ant-design-vue'。说白了unplugin-vue-components不知道你需要这个组件，通过查看compnents.d.ts里没有AMessage就证实了这个事。
解决方式有两种：

1. 随便一个有效组件template内引入一下
`<template>
.....
<a-message></a-message>
.....
</template>`
2. 手动导入message的同时手动导入message样式
`import { message } from 'ant-design-vue'
import 'ant-design-vue/es/message/style/index'`

**Comment by daiwanxing** [comment]
我感觉这个是unplugin-vue-component未能识别到部分UI库的可以通过js调用生成的组件，从而没有加载对应的样式。目前的可行的办法就是如楼上所说手动去导入对应的样式文件了

**Comment by codesyofo** [comment]
```js
import AutoImport from 'unplugin-auto-import/vite';

AutoImport({
  resolvers: [VantResolver()],
})
```

```vue
VanToast('提示内容');
VanDialog({ message: '提示' });
```

**Comment by zhangjingrm** [comment]
我是用的jsx语法，button组件也不能正确识别样式哎，必须要手动导入吗

**Comment by Cleam** [comment]
https://antdv.com/docs/vue/getting-started-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD

![image](https://user-images.githubusercontent.com/4132185/177456442-bb12c5ad-c4e1-4caa-8c1b-bb14504d7283.png)

**Comment by luocong2016** [comment]
> vant 的 toast 也是没有样式，一直以为只有我自己遇到这个问题呢，结果遇到难兄难弟了

function 形式的是不会自动导入，要手动引入

**Comment by ILfengzi** [comment]
已收到！
