### ISSUE TITLE
dts generation issue with webpack 5

### ISSUE THREAD

**Issue by WaqasIbrahim** [antfu/unplugin-vue-components#163]
Hi, I am having two issues in dts file generation using webpack. First of all, dts file is not generated atuomatically by detetcing typescript installation, which is not a big deal. Second issue is a big one, if there is already a dts file present, webpack will keep rebuilding in watch mode without any changes to any file.

Use this repo to reproduce this bug:
https://github.com/WaqasIbrahim/unplugin-vue-components-dts

Preview of the issue:

https://user-images.githubusercontent.com/12554146/135239304-19166499-7590-47c1-ba6a-bc71932271db.mp4

Edit: Ignoring `components.d.ts` solves the issue.
```js
watchOptions: {
    ignored: path.resolve(__dirname, 'components.d.ts'),
},
```

Can this configuration be added using unplugin so users don't have to manually ignore this file?

**Comment by antfu** [comment]
Please try with 0.15.6

**Comment by WaqasIbrahim** [comment]
Working great now. File is still not auto generated I need to add `dts: true` but that's not a big deal. Thanks
