### ISSUE TITLE
dts leaks absolute paths

### ISSUE THREAD

**Issue by FallDownTheSystem** [antfu/unplugin-vue-components#166]
With dts enabled, the GlobalComponents interface now uses absolute paths for components, causing user paths to be leaked. Previously all paths were relative.

For reproduction I simply cloned [vitesse](https://github.com/antfu/vitesse)
and ran `pnpm i` and `pnpm dev`. After that the `src/components.d.ts` file had changed to

```ts
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('C:/Users/MyUserName/Downloads/vitesse-main/src/components/Footer.vue')['default']
    README: typeof import('C:/Users/MyUserName/Downloads/vitesse-main/src/components/README.md')['default']
  }
}

export { }
```

This is on Windows 10 Version 21H2 (OS Build 19044.1263)

**Comment by antfu** [comment]
I don't have Windows to test so I might need some help here. The fix should be straightforward to check `isAbsolute` here

https://github.com/antfu/unplugin-vue-components/blob/872019591a925dcb2af326a651005eb712cb9b5d/src/core/declaration.ts#L22

**Comment by FallDownTheSystem** [comment]
I tested
```js
const related = isAbsolute(path)
          ? `./${relative(dirname(filepath), path)}`
          : path
```
And this seems to be working on Windwos at least.

**Comment by antfu** [comment]
Would you might to send a PR so you can have the credit?
