### ISSUE TITLE
Auto import of Vue components don't work in <script> section.

### ISSUE THREAD

**Issue by julie777** [antfu/unplugin-vue-components#169]
All my vue components are automatically imported for use in the template section of the Vue file. However, when I used a component in the script section it was undefined. 
```
$q.dialog({
    component: QuickAddDialog,
  })
```
There is really no documentation in the readme so I don't know if use of auto import into the script sections should work.

BTW, I love being able to get rid of all the component imports. That along with script setup has reduce my vue files to essential information/code.

**Comment by antfu** [comment]
This plugin only does component auto-import in templates, in your case you will need to import the component directly in scripts.

**Comment by julie777** [comment]
Thanks. A note in the readme would be helpful.
