### ISSUE TITLE
vscode can't "go to definition" for auto imported vue components

### ISSUE THREAD

**Issue by julie777** [antfu/unplugin-vue-components#177]
If discussions were enabled for this project I would have started one instead of creating an issue.

I love unplugin-vue-components. Given the regularity of directory structure, file naming and auto naming of the components it makes sense just to infer the imports and make them implicit. However, I realized that I often "jump to definition" in vscode. Apparently vscode was doing that based on import statements and doesn't work without them.

I am hoping that someone who knows how vscode works can provide a solution for this that can be added to unplugin-vue-components.

**Comment by antfu** [comment]
For me, with Volar it works. Can you share more info about what you are using?

**Comment by julie777** [comment]
> 
> 
> Have you enabled `dts: true`?

When I enabled dts:true then go-to-definition in vscode opens the components.d.ts file instead of going to the component file.

Also, when components.d.ts is opened eslint gives an error for the file "missing semicolon"

**Comment by acidjazz** [comment]
![vscode-component-click](https://user-images.githubusercontent.com/967369/141391213-0b396631-6c92-42d8-ac82-175f651c0d44.gif)

here is detailed replication

**Comment by lilu1814** [comment]
you can try vue-helper plugin in vscode

**Comment by mitow7821** [comment]
Any update on this? It looks like this problem still persist.

**Comment by richex-cn** [comment]
@antfu I have a similar problem, And I created an example using vite: https://github.com/richex-cn/issue-unplugin-vue-components-vscode

Component type cannot be inferred correctly in vscode:

![20220501_153927_SP](https://user-images.githubusercontent.com/25103518/166137012-9569d3b3-7a3d-4c60-b4e6-192a88abec27.png)

I tried to clone [Vitesse](https://github.com/antfu/vitesse) and use vscode locally. It can work normally. What did I miss?

![image](https://user-images.githubusercontent.com/25103518/166137104-7421dd31-fbbf-4a93-894d-29c12295dd87.png)

**Comment by sondh0127** [comment]
> @antfu I have a similar problem, And I created an example using vite: [richex-cn/issue-unplugin-vue-components-vscode](https://github.com/richex-cn/issue-unplugin-vue-components-vscode)
> 
> Component type cannot be inferred correctly in vscode:
> 
> ![20220501_153927_SP](https://user-images.githubusercontent.com/25103518/166137012-9569d3b3-7a3d-4c60-b4e6-192a88abec27.png)
> 
> I tried to clone [Vitesse](https://github.com/antfu/vitesse) and use vscode locally. It can work normally. What did I miss?
> 
> ![image](https://user-images.githubusercontent.com/25103518/166137104-7421dd31-fbbf-4a93-894d-29c12295dd87.png)

![image](https://user-images.githubusercontent.com/62163604/167307221-dc78f6e7-c534-4d76-a7f2-b77253eb8959.png)
add `shamefully-hoist=true` then reinstall will help

**Comment by richex-cn** [comment]
@sondh0127 Great! It work now, I'm noticed this configuration is also available [in Vitesse](https://github.com/antfu/vitesse/blob/0b31e5397d77495aa680f61209974bfbbbb862a4/.npmrc). Thank you!

But this is highly discouraged in [pnpm](https://pnpm.io/cli/install#--shamefully-hoist), I wonder if there is a better way to deal with it……

**Comment by sondh0127** [comment]
![image](https://user-images.githubusercontent.com/62163604/167308760-59f974ad-d70e-4aa6-9cda-288ad17924fc.png)
I'm not sure about this way is better or not. But we can re-add `@vue/runtime-core` to devDependencies, which to tell `pnpm` put it at first level of node_modules then the `import` above will match

**Comment by sondh0127** [comment]
I'm also notice that my current Volar version can detect with the old way of `declare` `vue`
![image](https://user-images.githubusercontent.com/62163604/167308994-42dd0222-ab22-4b49-81b7-c8186f183276.png)

**Comment by richex-cn** [comment]
After re-add `@vue/runtime-core` core to devDependencies, it work normally. One reason I can think of not recommending is that this will lead to hidden dangers when maintaining Vue versions in the project, Developers may need to pay attention to two dependent versions at any time.

As I tried to understand the reason, I had some confusion:

In Volar, The GlobalComponents define from `vue`, see here:
https://github.com/johnsoncodehk/volar/blob/de487c165ebec13b4e345f6a582ddd99c0c9a8b4/packages/vue-typescript/src/utils/localTypes.ts#L51-L52

But why does the document say `@vue/runtime-core` ? ses here:
https://github.com/johnsoncodehk/volar/blob/de487c165ebec13b4e345f6a582ddd99c0c9a8b4/extensions/vscode-vue-language-features/README.md?plain=1#L91-L95

It seems that this is why [defining GlobalComponents to 'vue'](https://github.com/antfu/unplugin-vue-components/issues/177#issuecomment-1120460976) works normally.

How should I understand it ? @johnsoncodehk @sondh0127 Thanks.

Some related:
https://github.com/antfu/unplugin-vue-components/issues/343
https://github.com/antfu/unplugin-vue-components/issues/355#issuecomment-1098939308

**Comment by antfu** [comment]
https://github.com/antfu/vscode-goto-alias should solves this.
