### ISSUE TITLE
css assets got wrong order after building

### ISSUE THREAD

**Issue by CaiWenlie** [antfu/unplugin-vue-components#182]
I use vite vue 3 with AntDesign, recently found that after running 'npm run build', the css assets is not in correct order.
usually the `vendor` should go before `common`, if not, some custom css will be covered by third-party css.

![image](https://user-images.githubusercontent.com/8305535/137279773-da601c25-6b9a-408a-bda4-cfc249ad19f7.png)

here is the config
```
  ViteComponents({
      dts: true,
      resolvers: [
        AntDesignVueResolver({
          importStyle: 'less',
          resolveIcons: true
        })
      ]
    }),
`

**Comment by antfu** [comment]
They also have different hash... maybe something wrong with your config? But either way, there is no guarantee that the CSS is imported in order. You should explicitly import them beforehand if the order of them matters.

**Comment by CaiWenlie** [comment]
> They also have different hash... maybe something wrong with your config? But either way, there is no guarantee that the CSS is imported in order. You should explicitly import them beforehand if the order of them matters.

different hash? emm... it's just js and css, i mean the css should be in same order with js, vendor goes before. thought it's related with the auto importing of ant components css. my custom css has been covered by it.

**Comment by npmrun** [comment]
bro, have you solved this yet, i have the same problem @CaiWenlie

**Comment by CaiWenlie** [comment]
> bro, have you solved this yet, i have the same problem @CaiWenlie

FYI. https://juejin.cn/post/6938351367517896712
