### ISSUE TITLE
[Feature Request] auto import Element Plus directive

### ISSUE THREAD

**Issue by sxzz** [antfu/unplugin-vue-components#183]
Track #179

**Comment by sxzz** [comment]
Add in 78639c439d3d65c57825dba834e8d3d518c347a5

**Comment by Fanna1119** [comment]
This issue is still present.

**Comment by Fanna1119** [comment]
I still need to do.

```js

import { ElLoading } from 'element-plus'

app.use(ElLoading)

```

**Comment by 838239178** [comment]
> Added in [78639c4](https://github.com/antfu/unplugin-vue-components/commit/78639c439d3d65c57825dba834e8d3d518c347a5)

noooooooooooooooooooo work

**Comment by pungfen** [comment]
> > Added in [78639c4](https://github.com/antfu/unplugin-vue-components/commit/78639c439d3d65c57825dba834e8d3d518c347a5)
> 
> noooooooooooooooooooo work

请问你解决这个问题了吗？我的项目里指令仍然不行(v-loading)，奇怪的是，官方的vite-start-template里居然是可以的！！！

**Comment by nooooooom** [comment]
```ts
import type Vue from 'vue'
import { Loading } from 'element-ui'

import 'element-ui/lib/theme-chalk/loading.css'

export function setupElementUI(app: typeof Vue) {
  app.use(Loading.directive)
}
```
