### ISSUE TITLE
vuetify don't import v-spacer

### ISSUE THREAD

**Issue by skimmilk6877** [antfu/unplugin-vue-components#184]
v-spacer is in VGrid folder, how to configure this problem?

**Comment by skimmilk6877** [comment]
when i look into the vite page, VSpacer is loaded

**Comment by martinussuherman** [comment]
@skimmilk6877 can you please setup a repo to reproduce the problem you've experienced? Looking at the code you give, I saw that the VSpacer was imported.

Regards,

Martinus

**Comment by skimmilk6877** [comment]
@martinussuherman sorry，I do not hava a small project，and because I met another problem with vuetify，I decided to wait for vuetify upgrade itselft for vite。
