### ISSUE TITLE
primevue tooltip

### ISSUE THREAD

**Issue by ga676005** [antfu/unplugin-vue-components#190]
I follow the installation of tooltip of PrimeVue https://primefaces.org/primevue/showcase/#/tooltip

It shows this error below when I use v-tooltip="'Click to proceed'" on an element.

![image](https://user-images.githubusercontent.com/51456572/139068234-6c0018ab-cccb-4fe1-b593-4ffc364e152a.png)

I think it is like the other components which have to be manually imported globally.
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/prime-vue.ts#L92

dependencies version:
```js
"unplugin-vue-components": "^0.16.0",  // this does not work

"unplugin-vue-components": "0.15.6"  // this works
```

**Comment by antfu** [comment]
Close via #191
