### ISSUE TITLE
ESM throw a Error 'Dynamic require of "element-plus/package.json" is not supported'

### ISSUE THREAD

**Issue by liuzw2579** [antfu/unplugin-vue-components#194]
in utils.ts function `getPkgVersion` use `require` to load 'package.json', but mjs file not have `require`

**Comment by liuzw2579** [comment]
> Could you please provide a minimum reproduction link?

When I create a vite plugin, package.json has `type: module`, it is a ESM pkg.

**Comment by nabaonan** [comment]
i start a pr use resolve method instead of require   , #232
