### ISSUE TITLE
"exclude" RegExp doesn't filter out matches

### ISSUE THREAD

**Issue by ksnyde** [antfu/unplugin-vue-components#195]
I have a library of VueJS components and in my `vite.config.ts` I have included **unplugin-vue-components** with the following config:

```ts
export default defineConfig({
    // ...
    plugins: [
       Components({ exclude: [ /docs\.vue/ ] }),
       // ...
    ]
});
```

Spread out across my `src/**` folders I have a number of components called `docs.vue` which are intended only for documentation purposes and are not exported as part of the library's primary export. So when I boot up the library's demo/doc site I get these warnings:

<img width="1484" alt="2021-10-28_17-46-10 (4)" src="https://user-images.githubusercontent.com/980757/139355229-319daa91-b58e-4195-8eca-22fc9d2583e9.png">

Now admittedly they don't stop me from doing anything but I figured my _exclude_ RegExp would have eliminated these warnings.

**Comment by antfu** [comment]
`exclude` is actually for transforming targets. For your case, you might want to use negative globs for them
https://github.com/antfu/unplugin-vue-components/blob/3ecdeade011d0ad4dde853ac48c3a051ba880420/src/types.ts#L63-L68
Or enable namespaces
https://github.com/antfu/unplugin-vue-components/blob/3ecdeade011d0ad4dde853ac48c3a051ba880420/src/types.ts#L76-L80
