### ISSUE TITLE
new components are not found and imported

### ISSUE THREAD

**Issue by julie777** [antfu/unplugin-vue-components#199]
I am using quasar which is using webpack for packaging.

When I create a new component file in the components directory and then refer to it in an existing component it is not automatically found and imported by unplugin-vue-components. In this case I have to add the import statement to get it to work.

I just ran another quick check. It doesn't work for a hot reload when the server is running and I modify the file, but if I stop the server and run "quasar dev" again to recompile/repackage everything it works.

**Comment by prestonholt** [comment]
I'm also having the same issue with webpack when using `webpack --watch`. New components aren't discovered until a full rebuild

**Comment by TimofeyBiryukov** [comment]
+1

**Comment by gouwa626** [comment]
+1

**Comment by moreant** [comment]
+1
