### ISSUE TITLE
vite build take a long time when Automatically introduce some custom components

### ISSUE THREAD

**Issue by qc-z** [antfu/unplugin-vue-components#204]
When I use unplugin Vue components to automatically import my custom components, vite packaging is very slow, with a time of 80 seconds, but when I manually import it, the packaging time is 20 seconds

![B8EDC82F-EF91-4D19-956E-69B94BC91648](https://user-images.githubusercontent.com/22362903/140604252-2c137e5a-c221-47f8-9054-25c1eb3b9f43.png)

**Comment by antfu** [comment]
I would need to reproduction to have a closer look

**Comment by qc-z** [comment]
[demo](https://github.com/qc-z/testbuild)
page: src/views/NewTask.vue 
line: 54 55

**Comment by pjcollazo** [comment]
Was there a resolution for this?
