### ISSUE TITLE
在使用CDN后相关配置可能有冲突导致按需加载组件未被打包

### ISSUE THREAD

**Issue by lancemach** [antfu/unplugin-vue-components#211]
我按照 README.md 中的配置依次配置后，在开发模式下是正常可以按需加载的，
按照vite的配置使用了CDN 

CDN 配置
```
// html
<script src="https://cdn.jsdelivr.net/npm/vue@3.2.16/dist/vue.global.prod.js"></script>

// vite
 rollupOptions: {
      // indicate which modules should be treated as external,
      external: ['vue'],
      plugins: [
        externalGlobals({
          vue: 'Vue'
        })
      ]
 }
```
在打包编译后发现，vue按需加载的组件是未被打包的 demo 我放在了 [github](https://github.com/lancemach/vite-v3)
请问一下，这两者是有冲突的地方还是，不能按照我的这种想法去实现呢，请指教，不胜感激

**Comment by bianyinglong** [comment]
> 我按照 README.md 中的配置依次配置后，在开发模式下是正常可以按需加载的， 按照vite的配置使用了CDN
> 
> CDN 配置
> 
> ```
> // html
> <script src="https://cdn.jsdelivr.net/npm/vue@3.2.16/dist/vue.global.prod.js"></script>
> 
> // vite
>  rollupOptions: {
>       // indicate which modules should be treated as external,
>       external: ['vue'],
>       plugins: [
>         externalGlobals({
>           vue: 'Vue'
>         })
>       ]
>  }
> ```
> 
> 在打包编译后发现，vue按需加载的组件是未被打包的 demo 我放在了 [github](https://github.com/lancemach/vite-v3) 请问一下，这两者是有冲突的地方还是，不能按照我的这种想法去实现呢，请指教，不胜感激

我也遇到了同样的问题，我使用的是vue-cli4.x在使用externals剔除第三方组件采用cdn加载时按需加载的组件并没有被打包到项目中，请问您是怎么解决的呢？

**Comment by lancemach** [comment]
> > 我按照 README.md 中的配置依次配置后，在开发模式下是正常可以按需加载的， 按照vite的配置使用了CDN
> > CDN 配置
> > ```
> > // html
> > <script src="https://cdn.jsdelivr.net/npm/vue@3.2.16/dist/vue.global.prod.js"></script>
> > 
> > // vite
> >  rollupOptions: {
> >       // indicate which modules should be treated as external,
> >       external: ['vue'],
> >       plugins: [
> >         externalGlobals({
> >           vue: 'Vue'
> >         })
> >       ]
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在打包编译后发现，vue按需加载的组件是未被打包的 demo 我放在了 [github](https://github.com/lancemach/vite-v3) 请问一下，这两者是有冲突的地方还是，不能按照我的这种想法去实现呢，请指教，不胜感激
> 
> 我也遇到了同样的问题，我使用的是vue-cli4.x在使用externals剔除第三方依赖包采用cdn加载时按需加载的组件并没有被打包到项目中，请问您是怎么解决的呢？

我找了好多资料，都没有这块的信息，我这个问题现在还在搁置，看官方能做出解答不，或者我找到了解决方案我在这联系你，如果你也找到了也请告知我，谢谢

**Comment by bianyinglong** [comment]
> 我找了好多资料，都没有这块的信息，我这个问题现在还在搁置，看官方能做出解答不，或者我找到了解决方案我在这联系你，如果你也找到了也请告知我，谢谢

我的问题已经解决了，参考我提的issues：https://github.com/antfu/unplugin-vue-components/issues/227
另外我发现vue的不同版本和element-plus版本可能会存在冲突问题，可以去codesandbox测试下找到不冲突的vue和element-plus版本再引入cdn，但是不知道你用的是什么组件库，希望能帮助到你

**Comment by zzzz-Z** [comment]
> > > 我按照 README.md 中的配置依次配置后，在开发模式下是正常可以按需加载的， 按照vite的配置使用了CDN
> > > CDN 配置
> > > ```
> > > // html
> > > <script src="https://cdn.jsdelivr.net/npm/vue@3.2.16/dist/vue.global.prod.js"></script>
> > > 
> > > // vite
> > >  rollupOptions: {
> > >       // indicate which modules should be treated as external,
> > >       external: ['vue'],
> > >       plugins: [
> > >         externalGlobals({
> > >           vue: 'Vue'
> > >         })
> > >       ]
> > >  }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在打包编译后发现，vue按需加载的组件是未被打包的 demo 我放在了 [github](https://github.com/lancemach/vite-v3) 请问一下，这两者是有冲突的地方还是，不能按照我的这种想法去实现呢，请指教，不胜感激
> > 
> > 
> > 我也遇到了同样的问题，我使用的是vue-cli4.x在使用externals剔除第三方依赖包采用cdn加载时按需加载的组件并没有被打包到项目中，请问您是怎么解决的呢？
> 
> 我找了好多资料，都没有这块的信息，我这个问题现在还在搁置，看官方能做出解答不，或者我找到了解决方案我在这联系你，如果你也找到了也请告知我，谢谢

找到解决方法了没  这官方也不看看这个问题 
我也是只要把vue使用cdn加载 所有自动引入的组件打包后都没有被编译了

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by richex-cn** [comment]
https://github.com/antfu/unplugin-vue-components/issues/636#issuecomment-1566987730

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
