### ISSUE TITLE
when i use ElementPlusResolver and use '@vitejs/plugin-legacy' in chrome 60, some dependence is gone

### ISSUE THREAD

**Issue by qc-z** [antfu/unplugin-vue-components#212]
![image](https://user-images.githubusercontent.com/22362903/141940185-92ec3e0e-3f1e-478c-b635-6f769cf137a0.png)

**Comment by xwnwho** [comment]
same problem.

**Comment by sxzz** [comment]
Could you please provide a minimum reproduction link?

**Comment by qc-z** [comment]
https://github.com/qc-z/testbuild
@sxzz

**Comment by baiyoung** [comment]
same problem. hope to deal with it as soon as possible, thank you
