### ISSUE TITLE
Component.d. ts could not find the module or its corresponding type declaration

### ISSUE THREAD

**Issue by jahnli** [antfu/unplugin-vue-components#214]
An error occurs when a component I wrote myself is imported
Component.d. ts could not find the module or its corresponding type declaration

![image](https://user-images.githubusercontent.com/20943608/141942406-c4ab5bcf-29b4-4652-95be-d72196d0d119.png)

![image](https://user-images.githubusercontent.com/20943608/141942244-e5b97cf6-df98-4066-b7c9-eead1694af09.png)

**Comment by bianyinglong** [comment]
> An error occurs when a component I wrote myself is imported Component.d. ts could not find the module or its corresponding type declaration
> 
> ![image](https://user-images.githubusercontent.com/20943608/141942406-c4ab5bcf-29b4-4652-95be-d72196d0d119.png)
> 
> ![image](https://user-images.githubusercontent.com/20943608/141942244-e5b97cf6-df98-4066-b7c9-eead1694af09.png)

I also encountered the same problem, have you solved it now?

**Comment by jahnli** [comment]
Place the automatically generated component.d.ts in the SRC directory

**Comment by bianyinglong** [comment]
> Place the automatically generated component.d.ts in the SRC directory

感谢，错误消失了

**Comment by JianJroh** [comment]
> 

better way : Make sure you also add components.d.ts to your tsconfig.json under includes [tips form](https://github.com/antfu/unplugin-vue-components#:~:text=Make%20sure%20you%20also%20add%20components.d.ts%20to%20your%20tsconfig.json%20under%20includes)
