### ISSUE TITLE
[feature request] Composition api and composables

### ISSUE THREAD

**Issue by Rigo-m** [antfu/unplugin-vue-components#215]
Would it be possible/interesting to extend this plugin or to make a new one for auto loading vue composition api functions and composables (a-la nuxt 3)?

**Comment by userquin** [comment]
@Rigo-m see `unplugin-auto-import`

**Comment by Rigo-m** [comment]
My bad, I've looked for it but couldn't find it.
My google skills are not so sharp i guess 😂
