### ISSUE TITLE
naive ui 引入报错

### ISSUE THREAD

**Issue by zcCodeWarehouse** [antfu/unplugin-vue-components#217]
Uncaught SyntaxError: The requested module '/node_modules/.vite/naive-ui.js?v=fb89fadc' does not provide an export named 'NEl'

**Comment by Talljack** [comment]
naive-ui没有导出NEI 请使用NElement

**Comment by Talljack** [comment]
ref https://github.com/TuSimple/naive-ui/pull/1739

**Comment by Talljack** [comment]
PR is merged, You can close this issue. @antfu
