### ISSUE TITLE
No components found with Jenkins

### ISSUE THREAD

**Issue by chengpeiquan** [antfu/unplugin-vue-components#220]
Hi, Anthony

In my company project, when I run `yarn build` to build it in Local or Server, no problem.

But when I use CI / CD with Jenkins, It throw the log "[unplugin-vue-components] no components found".

![1](https://user-images.githubusercontent.com/24845958/142790104-f2c243a5-0e4f-45f3-b8a4-4ed70bcf1a36.png)

Although it doesn't affect the building process, but these global components cannot be rendered.

I can't found how to fix it, this is my config, can you help me?

```ts
// vite.config.ts
import components from 'unplugin-vue-components/vite'
// ...
export default defineConfig({
  // ...
  plugins: [
    // ...
    components({
      dirs: [
        'src/components',
        'src/components/Admin',
        'src/components/Admin/GroupPanel',
      ],
      extensions: ['vue', 'ts'],
      deep: false,
      dts: false,
    }),
    // ...
  ],
})
```

**Comment by antfu** [comment]
Consider using the absolute path for dirs.

**Comment by chengpeiquan** [comment]
Good idea! I adjusted the config like this and waited for our DevOps engineer to try it later.
I believe there should be no problem this time hahahaha, I will update the result feedback when he takes care of it.

```diff
// vite.config.ts
import components from 'unplugin-vue-components/vite'
+ import path from 'path'
+ const resolve = (dir: string): string => path.resolve(__dirname, dir)

// ...
export default defineConfig({
  // ...
  plugins: [
    // ...
    components({
      dirs: [
-        'src/components',
-        'src/components/Admin',
-        'src/components/Admin/GroupPanel',
+        resolve('src/components'),
+        resolve('src/components/Admin'),
+        resolve('src/components/Admin/GroupPanel'),
      ],
      extensions: ['vue', 'ts'],
      deep: false,
      dts: false,
    }),
    // ...
  ],
})
```

**Comment by chengpeiquan** [comment]
Oh no, he said the problem still exists, but there are no other error log, only `[unplugin-vue-components] no components found`

**Comment by chengpeiquan** [comment]
After a few days of investigation, the cause was finally located! The problem is caused by the mismatch between the Jenkins workspace and the real path of the file.

**Comment by Rokixy** [comment]
I got the same problem. Could you tell me how did you fix this? @chengpeiquan 

> mismatch between the Jenkins workspace and the real path of the file

**Comment by chengpeiquan** [comment]
> I got the same problem. Could you tell me how did you fix this? @chengpeiquan
> 
> > mismatch between the Jenkins workspace and the real path of the file

At that time, the DevOps engineer in charge of Jenkins had left, and the conversation with him could not be queried. I remember that the workspace was originally named using Chinese brackets, such as `project_name（测试服）` , he thought that the workspace name was just a reading identification, but it actually seemed to affect the path reading of the file during packaging,which was later changed to `project_name_dev`, it works fine. Hope it can help you! @Rokixy
