### ISSUE TITLE
cannot find name

### ISSUE THREAD

**Issue by whace** [antfu/unplugin-vue-components#222]
when i use jsx.  cannot find name 'ElButton'.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by whace** [comment]
![1](https://user-images.githubusercontent.com/20571798/143968409-386e8c40-5233-4bcc-8d8a-c897eaa84314.png)
components.d.ts has generated, and components.d.ts has add to my tsconfig.json under includes.

**Comment by whace** [comment]
#221
