### ISSUE TITLE
TS：cannot find name ElComponent

### ISSUE THREAD

**Issue by whace** [antfu/unplugin-vue-components#223]
![image](https://user-images.githubusercontent.com/20571798/144035720-0cca4d6d-f5f0-4663-bdf3-bd564199e868.png)
components.d.ts has generated, and components.d.ts has add to my tsconfig.json under includes

**Comment by XPoet** [comment]
```
// tsconfig.json

"include": [
    ...
    "./*.d.ts"
  ],
```

**Comment by sxzz** [comment]
This plugin is not supported JSX, please try https://github.com/antfu/unplugin-auto-import
