### ISSUE TITLE
Antdv: Resolver cant resolve subcomponents like Paragraph from Typography

### ISSUE THREAD

**Issue by Fuzzyma** [antfu/unplugin-vue-components#228]
Imo this should just work:

```vue
<template>
  <AParagraph>...</AParagraph>
</template>
```

However, it fails because paragraph is not in `ant-design-vue/es/paragraph` but in `ant-design-vue/es/typography`

Can we get this solved?

**Comment by nabaonan** [comment]
i find the official demo is ` <a-typography>` , here is demo url   https://2x.antdv.com/components/typography-cn  @Fuzzyma
