### ISSUE TITLE
Antdv: Auto resolve kicks in before checking `components` field in component definition

### ISSUE THREAD

**Issue by Fuzzyma** [antfu/unplugin-vue-components#229]
When using ant components, using any component that starts with `A` will be resolved by the ant resolver even tho you might have specified such a component in the component definition:

```js
<template>
  <ABla/>
</template>

<script>
  import ABla from '...'
  
  export default {
    components: { ABla }
  }
</script>
```

The resolver will try to load it as ant component but obviously cant find it. This not only happens for known ant components but for ANY component starting with `A`

I found this to get around #228 like so:

```js
const { Title: ATitle, Paragraph: AParagraph } = Typography;
const { TextArea: ATextArea } = Input;

export default {
  components: { ATitle, AParagraph, ATextArea }
}
```

**Comment by nabaonan** [comment]
fixed in  https://github.com/antfu/unplugin-vue-components/pull/230
