### ISSUE TITLE
It happened  error after i add ElementUiResolver

### ISSUE THREAD

**Issue by wuaixiaoyao** [antfu/unplugin-vue-components#236]
![image](https://user-images.githubusercontent.com/22313713/144993790-7c13b9bf-c3d0-4697-a88f-de8f3eab3061.png)
![image](https://user-images.githubusercontent.com/22313713/144994055-ff4d94f2-4339-4301-89f3-e5f057bac2d1.png)
![image](https://user-images.githubusercontent.com/22313713/144993952-0a88037b-1be8-477c-be05-346d512e5912.png)

**Comment by sxzz** [comment]
This does not seem to be a problem with this plugin.
Please go to the element-plus repo to create an issue and **provide a reproduction link.** Without it, we can give any help to you.
