### ISSUE TITLE
component name change but dont delete old in d.t.ts

### ISSUE THREAD

**Issue by productdevbook** [antfu/unplugin-vue-components#237]
<img width="270" alt="CleanShot 2021-12-07 at 11 44 12@2x" src="https://user-images.githubusercontent.com/38668796/144996087-5e8ed14c-e788-4750-86d9-24f9a6bf808e.png">

components.d.ts
new:  MolTiptapBasic
old:  MolTiptapBasit

**Comment by antfu** [comment]
Well, this was a feature. But I found that a bit annoying too, PR welcome to fix it!

**Comment by Tanimodori** [comment]
Sometimes components used in async imported components will be deleted. I'm not sure whether it is related to this. I need some time to create a repro.
