### ISSUE TITLE
ElementPlusResolver issue with global setting

### ISSUE THREAD

**Issue by SunSeekerX** [antfu/unplugin-vue-components#239]
There are tow  ways config for element plus,here is the doc [quickstart](https://element-plus.gitee.io/zh-CN/guide/quickstart.html#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE)

```ts
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import App from './App.vue'

const app = createApp(App)
app.use(ElementPlus, { size: 'small', zIndex: 3000 })
```

```ts
import { createApp } from 'vue'
import App from './App.vue'

const app = createApp(App)
app.config.globalProperties.$ELEMENT = {
  // options
}
```

 I am using the second one

**The question is i can't change the default locale!**
```js
import zhCn from 'element-plus/lib/locale/lang/zh-cn'
app.config.globalProperties.$ELEMENT = {
  // options
  locale: zhCn,
  size: 'medium',
}
```

size config is working,but locale not.
if i use the `el-config-provider` for locale that is working

🤔🤔🤔 **I'd like to know is there have some way config in the `ElementPlusResolverOptions`**

**Comment by sxzz** [comment]
This does not seem to be a problem with this plugin.
Please go to the element-plus repo to create an issue and provide a reproduction link. Without it, we can't give any help to you.
