### ISSUE TITLE
按需引入Element-plus1.2.0-beta.6 无法正确加载样式路径

### ISSUE THREAD

**Issue by SmallWhiteRabbit** [antfu/unplugin-vue-components#254]
![image](https://user-images.githubusercontent.com/22906179/146858928-97795090-0f7d-4147-9cca-1013e23ff348.png)
查了文件路径 
Element-plus1.1.0  
      element-plus/es/components/menu/style/css.js
      element-plus/es/components/menu/style/css.td.js"；
 Element-plus1.2.0  
      element-plus\es\components\form\style\css.mjs  
      element-plus\es\components\form\style\css.d.ts 
      element-plus\es\components\form\style\css.mjs.map

**Comment by jackchoumine** [comment]
解决了吗？

**Comment by nabaonan** [comment]
我试了一下没有出现这个错误，版本是1.2.0 beta6 只按需加载了menu组件，能否给个复现

**Comment by yuanchen1** [comment]
like this

![image](https://user-images.githubusercontent.com/35587570/147854623-2baf25f2-3045-453c-ade5-895f353f3a80.png)

**Comment by yuanchen1** [comment]
like this in vite.config.js

![image](https://user-images.githubusercontent.com/35587570/147854638-23f2022e-0e96-4c44-a25a-d0796ef65851.png)

**Comment by yuanchen1** [comment]
vite.config.js 里面这样配置

![image](https://user-images.githubusercontent.com/35587570/147854676-fc3a5107-8750-49eb-ae18-a64e93a08145.png)

**Comment by SmallWhiteRabbit** [comment]
我把版本降到1.1.0了
我后面试下你发的引用方式看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月2日(周日) 凌晨0:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antfu/unplugin-vue-components] 按需引入Element-plus1.2.0-beta.6 无法正确加载样式路径 (Issue #254)




 
vite.config.js 里面这样配置
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SmallWhiteRabbit** [comment]
![1641349453(1)](https://user-images.githubusercontent.com/22906179/148150789-ee82b3fa-00e3-4068-bc81-89c98803d366.png)


> 我把版本降到1.1.0了 我后面试下你发的引用方式看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月2日(周日) 凌晨0:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [antfu/unplugin-vue-components] 按需引入Element-plus1.2.0-beta.6 无法正确加载样式路径 (Issue #254) vite.config.js 里面这样配置 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
![1641349453(1)](https://user-images.githubusercontent.com/22906179/148150820-dcb810bc-933e-4fb4-9410-c9222f7421e1.png)
我看了下源码 似乎是不支持component is 这种方式

**Comment by sxzz** [comment]
Please provide a minimum reproduction link.

**Comment by EsunR** [comment]
请问解决了吗？

**Comment by sxzz** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required
