### ISSUE TITLE
support ArcoResolver

### ISSUE THREAD

**Issue by catch6** [antfu/unplugin-vue-components#256]
the document has add Arco Design Vue, but the releases doesn't contain it
errer message:
```
error when starting dev server:
TypeError: (0 , import_resolvers.ArcoResolver) is not a function

```

**Comment by llk2yq** [comment]
+1

**Comment by sunlei4076** [comment]
also [https://github.com/Tencent/tdesign-vue-next](https://github.com/Tencent/tdesign-vue-next)

**Comment by llk2yq** [comment]
Can a new version be released today? @antfu
