### ISSUE TITLE
how to use with tsx?

### ISSUE THREAD

**Issue by qingtiantongxie** [antfu/unplugin-vue-components#259]
I  use vite vue  and ant-design in my project

my vite.config.js  
```
import vue from '@vitejs/plugin-vue'
import VueJsx from '@vitejs/plugin-vue-jsx'
import Components from 'unplugin-vue-components/vite'
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({
   plugins: [
    vue(),
    VueJsx(),
    Components({
      resolvers: [AntDesignVueResolver()],
      extensions: ['vue'],
      dts: true,
      include: [/\\.vue$/, /\\.vue\\?vue/, /\\.md$/],
    })
})
```

and in tsx file , i use Menu component and got ` 找不到名称“Menu”。ts(2304)`

**Comment by yeyunwen** [comment]
请问解决了吗
![1011716704272_ pic](https://github.com/unplugin/unplugin-vue-components/assets/87924100/5b405a51-d137-45f5-bdfd-4c8f1f014979)

**Comment by AzronChan** [comment]
@qingtiantongxie how to fix?

**Comment by yeyunwen** [comment]
我认为这不是unplugin-vue-components的问题，因为在template中是可以正常工作的，这个情况一般出现在script中，这个时候只需要手动导入对应的文件即可。
I don't think this is a problem with unplugin vue components, as they work normally in templates. This usually occurs in scripts, and at this point, you only need to manually import the corresponding file.

**Comment by yeyunwen** [comment]
> @qingtiantongxie how to fix?@qingtiantongxie如何解决？

我认为这不是unplugin-vue-components的问题，因为在template中是可以正常工作的，这个情况一般出现在script中，这个时候只需要手动导入对应的文件即可。
I don't think this is a problem with unplugin vue components, as they work normally in templates. This usually occurs in scripts, and at this point, you only need to manually import the corresponding file.
