### ISSUE TITLE
Vant配置按需导入后，无法及时生成组件props类型提示

### ISSUE THREAD

**Issue by yanbowe** [antfu/unplugin-vue-components#270]
![image](https://user-images.githubusercontent.com/43030980/147800042-3236f69d-11c0-4adf-897a-9850d8616738.png)
![image](https://user-images.githubusercontent.com/43030980/147800053-23a16b69-8994-4f2c-b117-2eda38f02326.png)
![image](https://user-images.githubusercontent.com/43030980/147800087-46d79864-75b5-42cf-b060-f26e5fb6ca1f.png)

tsconfig.json已设置引入components.d.ts，但是无法实时获得props提示，我每次需要手动去保存下tsconfig.json才会有对应的类型提示

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/147800193-618c5ee6-67a1-4279-8217-a844d24cecaa.png)
components.d.ts与src同级

**Comment by luocong2016** [comment]
## 试下配置加下
```js
ComponentsPlugin({
    dst: true,
 }),
```

**Comment by yanbowe** [comment]
> ## 试下配置加下
> ```js
> ComponentsPlugin({
>     dst: true,
>  }),
> ```

谢谢您，已解决

**Comment by henniliu** [comment]
> ## 试下配置加下
> ```js
> ComponentsPlugin({
>     dst: true,
>  }),
> ```
是dts
