### ISSUE TITLE
按需加载element-plus 无法显示badge样式，在message的grouping为true的时候

### ISSUE THREAD

**Issue by qc-z** [antfu/unplugin-vue-components#272]
"unplugin-vue-components": "0.17.11"
"element-plus": "1.3.0-beta.1"

![image](https://user-images.githubusercontent.com/22362903/148162694-55997755-edb2-4f16-8a8c-34f96b275915.png)

@sxzz

**Comment by sxzz** [comment]
Bug confirmed.

**Comment by sxzz** [comment]
Let track #5165.
