### ISSUE TITLE
Support nodejs v12?

### ISSUE THREAD

**Issue by stanleyxu2005** [antfu/unplugin-vue-components#276]
https://github.com/antfu/unplugin-vue-components/blob/a2134c6bfb089bf74a5882ebc6c51ddc019025c9/package.json#L110

Out of curiosity, does this plugin requires any feature of Nodejs v14? 
For some reason I have to stick with Windows 7, which can run Nodejs v12 only...
The whole tech stack is Nodejs v12, Vue v3, Webpack v5.

**Comment by zhanglolo** [comment]
I have used thsi plugin in my company pc which is win 7 and node version is 12.16.2, it build fail.

**Comment by sxzz** [comment]
I tested and it seems to work on Nodejs 12.

**Comment by sxzz** [comment]
Since nodejs 12 is about to end support, it makes sense that this plugin is not supported.
