### ISSUE TITLE
Can't detect new added component in windows 11

### ISSUE THREAD

**Issue by hasan-almujtaba** [antfu/unplugin-vue-components#281]
#### Issue description
 unplugin-vue-components can't detect new component in windows 11

#### Steps to reproduce the issue

1. clone vitesse as mentioned in readme 
2. add new component
3. use new component in page component

#### What's the expected result?

- component detected and can be used in other component

#### What's the actual result?

- error like in the screenshot below

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/52339597/149349243-534ed5cf-a551-4e41-95e4-5857013cd7aa.png)
![image](https://user-images.githubusercontent.com/52339597/149349366-6870f73b-892c-4db8-bdbb-822084208cef.png)

**Comment by Pawel2505** [comment]
The same problem. I added the simpliest vue and the simpliest component to the view and the problem ist the same.

**Comment by Ragura** [comment]
It does the same on Mac OS (Monterey 12.1), so it's not Windows 11 specific unfortunately.

**Comment by markthree** [comment]
hello，I tried to make a simple solution, listening to the files in the `components directory` and restarting the service after they were created.

This is a simple example 👇👇👇
```ts
// vite.config.ts
// You need to install @tyeps/node manually
import fs from 'fs'
import { version } from 'os'
import { watch } from 'chokidar' // file watcher，You need to install it manually
import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'

declare global {
  var $devServerInitStarted: boolean
}
setImmediate(() => {
   // This is to prevent chokidar from repeatedly listening during hot restart
   global.$devServerInitStarted = true
})

const isWindows11 = version() === 'Windows 10 Pro'

if (isWindows11 && !global.$devServerInitStarted) {
  const touch = (path: string) => {
	  const time = new Date()
	  try {
              fs.utimesSync(path, time, time)
	  } catch (err) {
              fs.closeSync(fs.openSync(path, 'w'))
	  }
  }
  
  watch('./src/components', { ignoreInitial: true }).on(
	  'add',
	  () => {
            touch('vite.config.ts')
	  }
    )
}

export default defineConfig({
   plugins: [Components(), Vue()]
})
```

See [tov-template](https://github.com/dishait/tov-template/tree/main/presets) for details!!

**Comment by markthree** [comment]
hello，The issue was solved，if you use windows, you can upgrade the plug-in to 0.17.17。See this PR for details 👉 [fix(normalizePath): windows to POSIX](https://github.com/antfu/unplugin-vue-components/pull/304)

**Comment by hasan-almujtaba** [comment]
thanks @markthree works like charm!

closing this issue.

**Comment by AndrewBogdanovTSS** [comment]
Issue is still reproducible on v.0.22., please, reopen
