### ISSUE TITLE
ElMessage is not define

### ISSUE THREAD

**Issue by Minori-ty** [antfu/unplugin-vue-components#285]
I use typescript

![image](https://user-images.githubusercontent.com/79521943/149687215-50dab618-ce7c-477c-b5cf-b1e61b170e4a.png)
![image](https://user-images.githubusercontent.com/79521943/149687219-d3da284a-02c7-45bd-88a2-9aed93cb0e60.png)

**Comment by sxzz** [comment]
This plugin is only for components. If you want to auto import `ElMessage` please consider to use https://github.com/antfu/unplugin-auto-import . Here is an example: https://github.com/sxzz/element-plus-best-practices
