### ISSUE TITLE
ant-design-vue: TimeRangePicker styleDir error

### ISSUE THREAD

**Issue by fx100** [antfu/unplugin-vue-components#286]
> Failed to resolve import "ant-design-vue/es/time-range-picker/style/css"
> ```bash
>   1  |  /* unplugin-vue-components disabled */import { Form as __unplugin_components_16 } from 'ant-design-vue/es';import 'ant-design-vue/es/form/style/css';
>   2  |  import { Row as __unplugin_components_15 } from 'ant-design-vue/es';import 'ant-design-vue/es/row/style/css';
>   3  |  import { TimeRangePicker as __unplugin_components_14 } from 'ant-design-vue/es';import 'ant-design-vue/es/time-range-picker/style/css';
>      |                                                                                          ^
>   4  |  import { TimePicker as __unplugin_components_13 } from 'ant-design-vue/es';import 'ant-design-vue/es/time-picker/style/css';
>   5  |  import { RangePicker as __unplugin_components_12 } from 'ant-design-vue/es';import 'ant-design-vue/es/date-picker/style/css';
> ```

**Comment by fx100** [comment]
#287

**Comment by sudongyuer** [comment]
I am trying to solve it now
