### ISSUE TITLE
vite.config.js中配置HeadlessUiResolver启动报错

### ISSUE THREAD

**Issue by zhangzesen** [antfu/unplugin-vue-components#294]
![image](https://user-images.githubusercontent.com/42395830/150709458-92690d1f-b0f3-48e0-8246-e09489ae8f1f.png)
在Components中添加HeadlessUiResolver会报Cannot read property 'prefix' of undefined，将HeadlessUiResolver注释掉可以正常运行

**Comment by ycs77** [comment]
現在暫時可以使用以下方式解決：

```js
export default defineConfig({
  plugins: [
    Components({
      resolvers: [
        HeadlessUiResolver({}), // 加上空的物件
      ],
    }),
  ],
})
```

如果 #300 被發布了之後，就可以直接更新到新版本了！
