### ISSUE TITLE
开发环境下可以优化启动性能吗？

### ISSUE THREAD

**Issue by luoyi58624** [antfu/unplugin-vue-components#301]
在开发环境下，直接全局引入Element-plus非常快，但使用插件解析组件库则需要花非常多的时间，打开浏览器页面一直在转圈圈，vite不停地在解析依赖，整个过程需要花费10多秒的时间，如果再引入其他依赖，那么时间将增大到半分钟

**Comment by asasugar** [comment]
+1 , 并且`element plus`按需引入，重新dev项目，如果没有浏览过使用某个组件（如：ElCard）的页面，则声明会自动删除，实际上组件有使用，只是没有访问过使用该组件的页面就会自动删除声明

**Comment by asasugar** [comment]
cc @antfu

**Comment by asasugar** [comment]
![image](https://user-images.githubusercontent.com/27256120/152905333-65e2e6d0-139a-47b7-a7e4-acf196120426.png)

**Comment by antfu** [comment]
It's not an issue of the plugin but rather Vite itself, we are already working on it https://github.com/vitejs/vite/pull/6758

**Comment by balck-paint** [comment]
@antfu Is this problem solved? As of today, I have updated to the latest version, but it is still very slow

**Comment by satrong** [comment]
Is it possible to add configuration to use full import in dev mode?

**Comment by zzzMaple** [comment]
still found the same problem in vite2.9.0 beta-3

**Comment by Corgis** [comment]
> vite@2.9.0-beta.7已解决该问题
你好请问现在有缓解么，我使用如下版本还是一样的很慢
"vite": "2.9.2",
"unplugin-auto-import": "^0.7.1",

**Comment by asasugar** [comment]
> > vite@2.9.0-beta.7已解决该问题
> > 你好请问现在有缓解么，我使用如下版本还是一样的很慢
> > "vite": "2.9.2",
> > "unplugin-auto-import": "^0.7.1",

用2.9.5就行，除了第一次慢点，或者依赖重装的话，因为在加缓存，node_modules/.vite/deps下

**Comment by Corgis** [comment]
好的 十分感谢
> 用2.9.5就行，除了第一次慢点，或者依赖重装的话，因为在加缓存，node_modules/.vite/deps下

**Comment by llcat** [comment]
```
"vite": "^3.0.9",
"unplugin-auto-import": "^0.11.2",
"unplugin-vue-components": "^0.22.4",
```
this issue still exist in vite 3.0+，now, i reslove it by full import in dev mode

**Comment by beikeliu** [comment]
![image](https://user-images.githubusercontent.com/49637524/191207452-ae70c57b-5fb8-43ac-af31-da8a2dbea635.png)
```json
    "unplugin-vue-components": "^0.22.7",
    "vite": "^3.0.9",
```

**Comment by like0413** [comment]
```json
"vite": "^4.1.4",
"unplugin-vue-components": "^0.24.1",
```
是的，现在还是如此，我不得不手动按需引入了

**Comment by beikeliu** [comment]
发送失败！

**Comment by shuqiang0** [comment]
我的一个很小的项目，开发环境首次加载时间能干到2-3分钟。UI库是ant-design-vue。体验极差。
