### ISSUE TITLE
Certain icons from `unplugin-icons` won't work?

### ISSUE THREAD

**Issue by AaronBeaudoin** [antfu/unplugin-vue-components#316]
`import CharmPackageIcon from "~icons/charm/package";` works as expected.

`http://localhost:3000/@id/~icons/charm/package` works as expected in the browser.

`<I-CharmPackage/>` does not work. I get the error:

```
[Vue warn]: Failed to resolve component: I-CharmPackage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index.page > 
  at etc...
```

My Vite config is like such:

```js
VueComponentsPlugin({
  resolvers: [
    ...
    IconResolver({
      prefix: "I",
      ...
    })
  ]
})
```

Other icons resolve without any issues. For example `<I-OcticonPackage16/>` works fine.

**Comment by ntnyq** [comment]
Icon collection `charm` is missed in 

https://github.com/antfu/unplugin-icons/blob/1a2de0f3e127deadbf5bd04a8948fb4c874a40ac/src/core/collections.ts#L2

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required
