### ISSUE TITLE
webpack5 ElementPlusResolver({ importStyle: 'sass' }) throw an error “@use rules must be written before any other rules”

### ISSUE THREAD

**Issue by jiangmugit** [antfu/unplugin-vue-components#328]
![image](https://user-images.githubusercontent.com/46895068/157157675-108465e2-1eba-49e3-aa38-1a602e131ca5.png)
![image](https://user-images.githubusercontent.com/46895068/157158007-bbe70dd0-8b3f-4f20-8a54-bd8c42a067bc.png)

**Comment by IAmRGroot** [comment]
I'm not sure if this is the same, but the error seems to origin from a sass update itself. Other packages are getting it as well, see https://github.com/vuetifyjs/vuetify/issues/13694#issuecomment-852957010 for example

**Comment by sxzz** [comment]
Reproduction please.
