### ISSUE TITLE
element-plus按需引入存在lodash插件

### ISSUE THREAD

**Issue by qujiahao** [antfu/unplugin-vue-components#330]
vue-cli4  "element-plus": "^2.1.4",
vue.config.js配置
Components({ 
	resolvers: [ElementPlusResolver()], // 自定义组件解析
	dts: false // 生成 `.d.ts` 全局声明, 
}),
只要使用element组件则打包lodash有五百多kb
<img width="688" alt="image" src="https://user-images.githubusercontent.com/37357218/158955206-6222c9a2-e314-4d3f-bb9a-c138aba72776.png">
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/37357218/158955343-585f52d0-8cef-4ba1-844b-374fa5e6a7f3.png">

**Comment by sxzz** [comment]
Not scope of this plugin. Please create a new issue to Element Plus repo with your reproduction repo.

P.S. I don't really recommend using Vue CLI 4 to build Vue 3 projects.
