### ISSUE TITLE
在Element-plus中使用 <component :is="componentId" ></component> 按需引入不会自动添加 style

### ISSUE THREAD

**Issue by lyh0371** [antfu/unplugin-vue-components#334]
```html
<template>
  <div>
    <el-button>你好</el-button>

    <component :is="componentId" v-model="val"></component>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { ElSelect } from 'element-plus';

const val = ref(true);
const componentId = ref(ElSelect);
</script>
```
![image](https://user-images.githubusercontent.com/30796346/159403850-9de1e216-87bc-40dd-a645-1eca9bdd72e8.png)

**Comment by sxzz** [comment]
`componentId` 是不可预测的。在运行时，它可以为任何组件。所以我认为超出了本插件的范围。
The `componentId` is unpredictable. At runtime, it can be for any component. So I think it is beyond the scope of this plugin.
