### ISSUE TITLE
vuecli5.0.3版本下创建的项目打包时components.d.ts文件内部import错误

### ISSUE THREAD

**Issue by PeyFon** [antfu/unplugin-vue-components#336]
vuecli：5.0.3
"unplugin-vue-components": "^0.18.1",
"unplugin-icons": "^0.14.0",
    "@iconify-json/ic": "^1.1.2",
    "@iconify-json/icon-park": "^1.1.1",

![image](https://user-images.githubusercontent.com/60815493/159608513-3ea7ec9e-366e-4aaa-a50d-c7ac437055d3.png)
![image](https://user-images.githubusercontent.com/60815493/159608765-7a6851c2-6e4b-4c4d-b028-fde35568cc71.png)
现象如下：
![image](https://user-images.githubusercontent.com/60815493/159609283-79e0ab98-4269-458a-a69a-318853ca7f55.png)
![image](https://user-images.githubusercontent.com/60815493/159609438-3337d803-c98c-4e89-9d6e-686cc63b16fa.png)

**Comment by PeyFon** [comment]
是因为自动引入了ic的原因吗

**Comment by 695648896** [comment]
@PeyFon 你好，我也遇到了这样的错误 请问是如何解决的？
