### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by ggglmc** [antfu/unplugin-vue-components#337]
如图，提示Error: Cannot find module 'unplugin-vue-components/vite'
![image](https://user-images.githubusercontent.com/31680174/159649405-9b9d7c20-a228-4b13-8bd1-261b92b3ed18.png)
![image](https://user-images.githubusercontent.com/31680174/159649466-774fc0a0-6abd-455e-be97-ff69ab4d68f4.png)

**Comment by zhanglolo** [comment]
安装了依赖吗？

**Comment by wl244704182** [comment]
看下node版本，好像只有14跟16可以

**Comment by sxzz** [comment]
Please provide more informations (node version, reproduction repo...)
