### ISSUE TITLE
Does this work with vue3-runtime-template?

### ISSUE THREAD

**Issue by merijnponzo** [antfu/unplugin-vue-components#34]
I added vite-plugin-components to my vite.config.js
I'm using a php stack with inertia and render runtime components with vue3-runtime-template

However, vue.esm-bundler.js says that my auto imported components can't be resolved.

the vue.esm-bundler.js is added as an alias 'vue'
```
resolve: {
      alias: {
        vue: 'vue/dist/vue.esm-bundler.js',
      },
    },
```
If i add 
```
import Tabs from './components/ui/Tabs.vue'
```
and
```
.component('Tabs', Tabs)
```
my Tab component is rendered within the vue3-runtime-template component

**Comment by antfu** [comment]
Not sure if I understand you here. Can you share a repo to show case what you are trying to do? Thanks

**Comment by merijnponzo** [comment]
Yes, it's a wordpress theme based on vite - inertia and vue3 with the lazyblocks plugin to create custom gutenberg blocks.

https://github.com/merijnponzo/innervite2
So I placed my tabs component within blocks/lazyblock-tabs/block.php 
```
<Tabs 
:theme='<?=json_encode($theme);?>'
:content='<?=json_encode($content);?>'
>
```
Which is well rendered within src/components/Gutenblocks.vue
Because I mount my Tab component within  src/app.js
```
import Tabs from './components/ui/Tabs.vue'
import Tab from './components/ui/Tab.vue'
createApp({
etc
.component('Tabs', Tabs)
```

But it would be easier to use the vite-plugin-components so I don't have to add all my components to src/app.js
Since i use runtime based components due the  vue3-runtime-template plugin i use the vue/dist/vue.esm-bundler.js

However, if i remove the .component('Tabs', Tabs) from src/app.js and add the component directory to the vite.config.js my Tab component is failed to resolved .

I guess the vite-plugin-components are not imported within this setup.
thanks

**Comment by merijnponzo** [comment]
the log says
```
[Vue warn]: Failed to resolve component: Tab 
runtime-core.esm-bundler.js:38:16
```
from resolveComponent=fn<resolveComponent> >
