### ISSUE TITLE
I can not start the dev server after added the AntDesignVueResolver 

### ISSUE THREAD

**Issue by justforbeatit** [antfu/unplugin-vue-components#342]
As the picture, i want to auto import ant-design-vue component in my project , and i configured it as the same as the offical document, but i can not start the dev server after do that,  is there anyone know what the problem is ?

![auto-import-error](https://user-images.githubusercontent.com/95928415/160230294-e135a0a6-3703-4bd6-bc82-549217f67d17.gif)

**Comment by adarshmadrecha** [comment]
@justforbeatit can you share Repo / codesandbox link?

**Comment by justforbeatit** [comment]
@adarshmadrecha  Thank you for your reply,  i have changed vue-cli to vite and  then it does not appear this problem

**Comment by adarshmadrecha** [comment]
Perfect. 
In that case, you can close this issue.
