### ISSUE TITLE
重新dev项目，如果没有浏览过使用某个组件（如：ElCard）的页面，则声明会自动删除，实际上组件有使用，只是没有访问过使用该组件的页面就会自动删除声明

### ISSUE THREAD

**Issue by free-pan** [antfu/unplugin-vue-components#347]
### 问题描述

element plus按需引入，重新dev项目，如果没有浏览过使用某个组件（如：ElCard）的页面，则声明会自动删除，实际上组件有使用，只是没有访问过使用该组件的页面就会自动删除声明

### 期望效果

只要我用到的依赖，无论我是否有访问对应界面，都能自动引入

### 补充信息

![image](https://user-images.githubusercontent.com/37232676/161225634-1302cdcb-52a3-4550-8977-8485134ce1fa.png)

**Comment by yornqiu** [comment]
Why clsoed this?
Did you solve the problem?
