### ISSUE TITLE
怎么自动导入Message、Notification等自定义方法？

### ISSUE THREAD

**Issue by chcici** [antfu/unplugin-vue-components#350]
只有写在template里的组件才能拿到name

**Comment by yornqiu** [comment]
If you used with unplugin-auto-import, you can do this:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/13913084/163533577-3ff841ad-a0bf-4754-81cc-49285761fd21.png">

Explicitly import in AotuImport options.

**Comment by sxzz** [comment]
Not really, you can refer to this template.
https://github.com/sxzz/element-plus-best-practices/blob/main/vite.config.ts#L21-L39

**Comment by YornQiu** [comment]
> Not really, you can refer to this template. https://github.com/sxzz/element-plus-best-practices/blob/main/vite.config.ts#L21-L39

But it doesn't work properly in some cases. As this issue: https://github.com/element-plus/element-plus/issues/6947.
And I still haven't found a perfect solution , so had to add the imports

**Comment by axsann** [comment]
In addition to [YornQiu's solution](https://github.com/antfu/unplugin-vue-components/issues/350#issuecomment-1099903363), you need to import css in the entry point js file.

```
import 'element-plus/theme-chalk/el-message.css';
import 'element-plus/theme-chalk/el-notification.css';
```
In app.js (entry point js)

**Comment by fayeah** [comment]
> In addition to [YornQiu's solution](https://github.com/antfu/unplugin-vue-components/issues/350#issuecomment-1099903363), you need to import css explicitly in the entry point js file.
> 
> ```
> import 'element-plus/theme-chalk/el-message.css';
> import 'element-plus/theme-chalk/el-notification.css';
> ```
> 
> In app.js (entry point js)

这个加了之后不用加imports 配置也能生效。
