### ISSUE TITLE
使用按需引入时，首次启动服务会依赖预构建style

### ISSUE THREAD

**Issue by CrabSAMA** [antfu/unplugin-vue-components#361]
![image](https://user-images.githubusercontent.com/40541269/163768339-7c5f2a72-0fe8-490b-be5f-2282ddd201a7.png)
问题现象：
使用 ant-design-vue + vite ，使用按需引入的方式，当首次启动 vite 服务时会对 style 进行依赖预构建，并且在切换不同路由时如果其他模块有使用到新的组件，页面会卡住直至 `dependencies optimized` 完成。
疑问：
想知道这个是 vite 的问题还是这个组件的问题呢？有什么办法可以解决吗？

插件使用：
![image](https://user-images.githubusercontent.com/40541269/163768806-f12402f3-0a1f-465c-9528-083896752ec0.png)

**Comment by yangss3** [comment]
我试了一下，element-plus 也有同样的问题，首次启动或者遇到新组件，加载会很慢。但是比 ant-design-vue 快一些，不知道是插件的问题还是组件的问题

**Comment by CrabSAMA** [comment]
@antfu 大佬cc

**Comment by lvjiaxuan** [comment]
> 我试了一下，element-plus 也有同样的问题，首次启动或者遇到新组件，加载会很慢。但是比 ant-design-vue 快一些，不知道是插件的问题还是组件的问题

原来是这样，我以为卡死了

**Comment by lvjiaxuan** [comment]
> 我试了一下，element-plus 也有同样的问题，首次启动或者遇到新组件，加载会很慢。但是比 ant-design-vue 快一些，不知道是插件的问题还是组件的问题

研究了下。发现是 antdv 使用了 babel-runtime，估计是巨多的 helps 函数导致 Vite 进行 Pre-Building 时极慢。试了element-plus、vant、arco 就没有太多依赖，就快点。

**Comment by xwnwho** [comment]
我也遇到了，使用的是ant-design-vue,有时候会导致menu菜单选中了，但是路由不会跳转（本地环境和正式环境都出现过）

**Comment by lvjiaxuan** [comment]
xdm，我来分享一波配置

`vite.config.ts`
```ts
{
  // ...
  Components({
    dts: './types/components.d.ts',
    resolvers: command === 'build' ? [ AntDesignVueResolver() ] : [],
  }),
  {
    name: 'main_ts-plugin',
    transform(code, id) {
      if (command === 'serve' && /main\.ts/.test(id)) {
        const importCode = 'import antdv from "ant-design-vue";\nimport "ant-design-vue/dist/antd.min.css";\n' + code
        const appUseCode = importCode.replace('app = createApp(App);', 'app = createApp(App);\napp.use(antdv);\n')
        return {
          code: appUseCode,
          map: null,
        }
      }
    },
  },
  // ...
}
```

`env.d.ts`
```ts
/// <reference types="ant-design-vue/typings/global" />
// ...
```

**Comment by lvjiaxuan** [comment]
> 我在用element-plus 开发也发现了这个问题，按需导入的新组件多就会卡死和刷新页面。 最后的解决方案是开发用全量导入组件，打包用按需导入。可以参考一下我的修改 [hminghe/md-admin-element-plus@be3cdf6](https://github.com/hminghe/md-admin-element-plus/commit/be3cdf6999d3ae349f79e31d32b2a49de1239fcc)

谢谢你，温暖了四季

**Comment by hooray** [comment]
我的做法是把 element plus 里会触发预构建的资源在运行一开始就手动进行预构建
https://github.com/hooray/fantastic-admin/blob/master/vite.config.js#L58-L60

**Comment by llcat** [comment]
😭 终于找到了相同的问题, 在vite issues区找了半天, 用element-plus也有, debug看vite:load一个小组件要40多秒, 经常卡死并导致页面刷新，开发体验好糟糕
![image](https://user-images.githubusercontent.com/17900822/188560131-370b8402-0a82-4350-8c4f-19513e293d4d.png)

**Comment by llcat** [comment]
> 我在用element-plus 开发也发现了这个问题，按需导入的新组件多就会卡死和刷新页面。 最后的解决方案是开发用全量导入组件，打包用按需导入。可以参考一下我的修改 [hminghe/md-admin-element-plus@be3cdf6](https://github.com/hminghe/md-admin-element-plus/commit/be3cdf6999d3ae349f79e31d32b2a49de1239fcc)

按照这种方式解决呢, 有大佬搞明白问题到底出在哪吗?

**Comment by sxzz** [comment]
Out of the scope of this plugin, please report it to the UI library repo.

**Comment by shuqiang0** [comment]
推荐使用按需加载，然后用了之后，感觉还没有webpack好用🥲

**Comment by AIxiuxiu** [comment]
按需加载element我是这样修改的，把所有组件的style添加到optimizeDeps的include中，ant-design-vue照着改下就行
```js
const optimizeDepsIncludes= ['vue', 'vue-router'];
fs.readdirSync(`./node_modules/element-plus/es/components`).map(dirname => {
  const exist = fs.existsSync(`./node_modules/element-plus/es/components/${dirname}/style/index.mjs`);
  if (exist) {
    optimizeDepsIncludes.push(`element-plus/es/components/${dirname}/style/index`);
  }
});
```

vite config中添加optimizeDeps
```js
 // 预加载项目必需的组件
  optimizeDeps: {
    include: optimizeDepsIncludes,
  },
```
