### ISSUE TITLE
编译报错，和 mini-css-extract-plugin 存在冲突

### ISSUE THREAD

**Issue by keuby** [antfu/unplugin-vue-components#363]
## 问题描述

使用 vue-cli 初始化应用后，同时注册 windicss-webpack-plugin 和 unplugin-vue-components 插件，在执行 `yarn build` 后编译报错

报错显示为 mini-css-extract-plugin loader 的 schema 校验 options 失败，调试看上去像是使用 mini-css-extract-plugin loader 的 schema 校验了 unplugin 的 loader options

## 脚手架搭建过程

1. 使用 vue create unplugin-bug-demo 创建应用
2. 安装 windicss-webpack-plugin unplugin-vue-components
3. 在 vue.config.js 的 configureWebpack.plugins 中注册这两个插件

## Reproduction

https://github.com/keuby/unplugin-bug-demo

## System Info

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 89.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 98.0.2
    Safari: 15.4
  npmPackages:
    unplugin-vue-components: ^0.19.3 => 0.19.3 
    windicss-webpack-plugin: ^1.6.10 => 1.6.10

Used package manager: yarn

## 报错信息
![image](https://user-images.githubusercontent.com/32365592/164132850-29841219-ee8a-436e-88fc-9ba41b8247a2.png)

**Comment by keuby** [comment]
已经解决了，是 windicss-webpack-plugin 插件的问题

https://github.com/windicss/windicss-webpack-plugin/issues/111

**Comment by alleluya-young** [comment]
> 已经解决了，是 windicss-webpack-plugin 插件的问题
> 
> [windicss/windicss-webpack-plugin#111](https://github.com/windicss/windicss-webpack-plugin/issues/111)
hola  看起来是不是我和你遇到的问题一样? 这个问题我应该是去vant提issue吗?
![image](https://user-images.githubusercontent.com/31433884/164687698-64108ec1-0e6f-48d3-be9c-363d47f40661.png)

**Comment by yoyo837** [comment]
> > 已经解决了，是 windicss-webpack-plugin 插件的问题
> > [windicss/windicss-webpack-plugin#111](https://github.com/windicss/windicss-webpack-plugin/issues/111)
> > hola  看起来是不是我和你遇到的问题一样? 这个问题我应该是去vant提issue吗?
> > ![image](https://user-images.githubusercontent.com/31433884/164687698-64108ec1-0e6f-48d3-be9c-363d47f40661.png)

同样的问题, 注释掉 unplugin-vue-components 就正常
