### ISSUE TITLE
components.d.ts has an error prompt.

### ISSUE THREAD

**Issue by Aizener** [antfu/unplugin-vue-components#367]
I tried to use `unplugin-vue-components` to automatically import components.
After the dependency is installed, the page can be displayed normally.
However, in `components.d.ts` file has the following prompts:

![image](https://user-images.githubusercontent.com/35794624/165707580-be9c64b4-9c56-439a-8ac4-0f4d9cd17837.png)

***Restarting vscode doesn't work either, but the page is displayed correctly.***

**Comment by Hyphon** [comment]
maybe a `shims-vue.d.ts` can help..

```ts
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}
```

**Comment by liuv3v6** [comment]
> 

It does't work. the default project template has env.d.ts that content is you provided

**Comment by liuv3v6** [comment]
> maybe a `shims-vue.d.ts` can help..
> 
> ```ts
> declare module '*.vue' {
>   import type { DefineComponent } from 'vue'
>   const component: DefineComponent<{}, {}, any>
>   export default component
> }
> ```

It does't work. the default project template has env.d.ts that content is you provided

**Comment by liuv3v6** [comment]
1. Run `Extensions: Show Built-in Extensions` from VS Code's command palette, look for `TypeScript and JavaScript Language Features`, then right click and select `Disable (Workspace)`. By default, Take Over mode will enable itself if the default TypeScript extension is disabled.
2. Reload the VS Code window by running `Developer: Reload Window` from the command palette.

above message provide in  vite template vue-ts  `readme.md` , I try, it's work!

**Comment by ycs77** [comment]
Include `components.d.ts` to `tsconfig.json` will be solved:

```json
{
  "compilerOptions": {
    ...
  },
  "include": [
    "components.d.ts", // <== add this line
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

**Comment by bittermeatball** [comment]
> Include `components.d.ts` to `tsconfig.json` will be solved:
> 
> ```json
> {
>   "compilerOptions": {
>     ...
>   },
>   "include": [
>     "components.d.ts", // <== add this line
>     "src/**/*",
>     "src/**/*.vue"
>   ]
> }
> ```

Thanks, this helps resolve the problem
