### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.1"

### ISSUE THREAD

**Issue by wishong** [antfu/unplugin-vue-components#368]
node 版本一定要14以上吗
我看 `0.14.13` 版本才加上的这个判断，之前的版本 node12 所有依赖包都是支持的
不知这个是否可以去掉😥
```
  "engines": {
    "node": ">=14"
  }
```

**Comment by sxzz** [comment]
Because node 12 has ended the LTS.
因为 node 12 已经结束了 LTS 的支持时间。

Is this a warning or an error report, if it is a warning you can ignore (at your own risk)
这是一个警告还是报错，如果是警告就可以忽略（风险自负）

**Comment by wishong** [comment]
> Because node 12 has ended the LTS. 因为 node 12 已经结束了 LTS 的支持时间。
> 
> Is this a warning or an error report, if it is a warning you can ignore (at your own risk) 这是一个警告还是报错，如果是警告就可以忽略（风险自负）

是报错，因为服务器上 node 版本为 12.x 导致无法安装依赖

**Comment by sxzz** [comment]
then fork it or update your node
