### ISSUE TITLE
ElementPlusResolver在解析使用element指令时并未自动导入样式表。

### ISSUE THREAD

**Issue by VioletAyatan** [antfu/unplugin-vue-components#369]
我在项目中使用这个插件时它打大部分情况下是正常工作的，但当我使用elment-plus指令时，它所需的样式表并未并导入进去。

![企业微信截图_16511382289892](https://user-images.githubusercontent.com/53887842/165723052-9ba47f39-4ad2-4fd6-a5be-69730feb1c44.png)

结果：

![企业微信截图_16511383204358](https://user-images.githubusercontent.com/53887842/165723261-951e840d-8d44-4ad5-ab08-a93e5b54963a.png)

我必须自己手动在`main.ts`文件引入css文件样式才正常显示。

![1](https://user-images.githubusercontent.com/53887842/165723631-1fee4e07-dbc5-4f54-a29e-cf418ca5110f.png)
![2](https://user-images.githubusercontent.com/53887842/165723646-53759aa4-5095-48b9-8817-e76da00bf122.png)

**Comment by sxzz** [comment]
https://element-plus.org/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5
