### ISSUE TITLE
Error: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by JesterHeads** [antfu/unplugin-vue-components#37]
Hi, I'm new to Vite and I wanted to try it with this plugin, but when I import the plugin and use it in vite.config.js
I get the following error :
![Capture d’écran 2021-04-14 à 12 59 09](https://user-images.githubusercontent.com/24459223/114699968-3c889e00-9d21-11eb-9313-3860a0040dac.png)

I don't really know what I'm doing wrong because it's really the first thing i've done after starting the project.
Here is my vite.config.js
```javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import ViteComponents from 'vite-plugin-components'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    ViteComponents()
  ]
})
```

**Comment by sampullman** [comment]
You probably need to post your whole project, or at least `App.vue` and directory structure.

**Comment by antfu** [comment]
What's your Node version?

**Comment by antfu** [comment]
Close due to inactive.
