### ISSUE TITLE
使用pnpm安装  components.d.ts 文件内 declare module '@vue/runtime-core' 无效

### ISSUE THREAD

**Issue by XHNLYW** [antfu/unplugin-vue-components#375]
使用pnpm安装后 node_modules内找不到@vue  components.d.ts内 declare module '@vue/runtime-core' 无效

**Comment by sondh0127** [comment]
![image](https://user-images.githubusercontent.com/62163604/167307221-dc78f6e7-c534-4d76-a7f2-b77253eb8959.png)
add `shamefully-hoist=true` then reinstall will help

**Comment by sxzz** [comment]
1. Method 1: enable `shamefully-hoist`
2. Method 2: install `@vue/runtime-core` as dev dependency.
