### ISSUE TITLE
antv的Row和Col组件自动导入后无法识别出属性

### ISSUE THREAD

**Issue by rainmanhhh** [antfu/unplugin-vue-components#379]
components.d.ts中已经生成了下面的类型定义
```typescript
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    //...
    ARow: typeof import('ant-design-vue/es')['Row']
    ACol: typeof import('ant-design-vue/es')['Col']
    //...
  }
}
```
但在vue文件中输入`:gutter`之类的属性时，不会自动补全，手动输入完了鼠标悬停也没有显示注释
其他很多组件都正常，如AInput，AForm等，就ARow和ACol不行

**Comment by hurole** [comment]
我这是正常
![](https://user-images.githubusercontent.com/32867828/173228252-e6442ac2-f3ee-4956-b688-38ee74bf9683.png)
的

**Comment by rainmanhhh** [comment]
你这是webstorm还是vscode？我用的idea，即使手动写了gutter等属性，也是提示为`Custom Vue component property`

**Comment by loosheng** [comment]
@rainmanhhh 
令人遗憾的是:
至今为止 ，在JetBrains 系 IDE （IDEA,WebStorm 等) 中 vue 文件的第三方组件库并不是使用 d.ts 提供的提示与类型校验（  IDE 层面 ）
而是使用一种 json 约束的格式 [Web-Types](https://github.com/JetBrains/web-types)
根据本 issue 创建日期，ant-design-vue 版本为 3.2.3
根据 unpkg 上 ant-design-vue 的 [ web-types  文件显示](https://unpkg.com/browse/ant-design-vue@3.2.3/vetur/web-types.json) 确实没有 `a-col` 与 `a-row` 标签（最新版也没有）,你应该向 ant-design-vue 参考提出 issue
此插件的 `components.d.ts` 文件的提示与类型校验（  IDE 层面 ）本质上对 JetBrains 系 IDE  vue 文件中的标签无效
此问题可以关闭，与本仓库无关
