### ISSUE TITLE
Discrepancy with rule `vue/prefer-import-from-vue`

### ISSUE THREAD

**Issue by dserv-nh** [antfu/unplugin-vue-components#393]
After updating to [eslint-plugin-vue v9.0.0](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.0.0) I see a violation of [`vue/prefer-import-from-vue`](https://eslint.vuejs.org/rules/prefer-import-from-vue.html) in `components.d.ts`

`Import from 'vue' instead of '@vue/runtime-core'.`

**Comment by doveccl** [comment]
> After updating to [eslint-plugin-vue v9.0.0](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.0.0) I see a violation of [`vue/prefer-import-from-vue`](https://eslint.vuejs.org/rules/prefer-import-from-vue.html) in `components.d.ts`
> 
> `Import from 'vue' instead of '@vue/runtime-core'.`

+1

**Comment by SegaraRai** [comment]
Seems to be fixed in [eslint-plugin-vue v9.1.0](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.1.0).
