### ISSUE TITLE
How to use this with unit tests?

### ISSUE THREAD

**Issue by eratio08** [antfu/unplugin-vue-components#41]
As this is a vite plugin it won't be utilized when running unit test and all components won't be transformed.
Is there any trick to get this working with the `vue-test-utils` / `jest`?

**Comment by husayt** [comment]
@antfu seems like quite a few people stumbling with this. Is there a solution for using this plugin with unit testing?

**Comment by antfu** [comment]
I would suggest to use cypress, which will just work.

**Comment by husayt** [comment]
Yes, but they are different things. I use cypress and that works fine. But what about testing components in isolation i.e. unit tests?

**Comment by marktnoonan** [comment]
@husayt Cypress has a component testing solution for Vue now that's built on top of Vue Test Utils + Vite - it came out in the last couple of major Cypress versions. This might be what @antfu is referring to. I haven't tested it with this package but I've been using it where I would have used jest component tests in the past: https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/

**Comment by sampullman** [comment]
I have high hopes for [vite-jest](https://github.com/sodatea/vite-jest), if/when that's stable it should solve this problem. I'm running in to the same issue with `vite-plugin-components`, and some of my own Vite plugins.

Another option is to write a standalone Jest transformer, maybe some of the internal plugin logic here can be reused.

**Comment by doutatsu** [comment]
Bumping this up - was really excited to make use of it, now that I migrated to Vue... but with 500+ unit tests, this needs to be fixed first 😬

**Comment by eratio08** [comment]
So the simple answer to this seems to be now: Use [vitest](https://github.com/vitest-dev/vitest) for testing!

**Comment by casey6** [comment]
> ⚠️ DISCLAIMER: Vitest is still in development and not stable yet. It's not recommended to use it in production.

**Comment by doutatsu** [comment]
^ Exactly. Vitest seems interesting, but it's not battle-tested like Jest is, so it's still be best to wait for vite-jest to ship

**Comment by TetianaPozniakovaClone** [comment]
@eratio08 how do you solve this with vitest? do you have any examples?

**Comment by eratio08** [comment]
@TetianaPozniakovaClone I did not try to use this plugin yet but using vite + vitest should allow to at least make the code injection/generation that is done by this plugin work that would not work with jest before. 
What kind of stubs are you talking about? Component Stubs or just general stubs/mocks? I never tried to stub components to far. I use vitest for mocking and vitest-mock-extended for typescript class/interface mocking. Where do your stubs need to be injected?

**Comment by TetianaPozniakovaClone** [comment]
@eratio08 yes, components stubs.
Here's my code:
`    const wrapper = mount(HomePage, {
      global: {
        mocks: {
          $t: (_) => _,
        },
        stubs: ['items-list'],
        plugins: [createTestingPinia()],
      },
    })`

And somehow items-list is only stubbed when I explicitly add:
`import ItemsList from '@/components/ItemsList.vue'`
to the HomePage. Otherwise, plugin just renders the whole component.

P.S. I think I should create a new thread for this :)

**Comment by eratio08** [comment]
Mh I never had a use case for stub components to I cant comment on that. I would just use `shallowMount`.

**Comment by Neophen** [comment]
> So the simple answer to this seems to be now: Use [vitest](https://github.com/vitest-dev/vitest) for testing!

This doesn't work with with stubs:

example:
```js
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/vue';

import SomeComponent from './SomeComponent.vue';

describe('SomeComponent', () => {
  it('should renders a card with props', async () => {
    const { html } = render(SomeComponent, {
      stubs: [
        'SomeComponentHeader',
      ],
    });

    expect(html()).toMatchSnapshot();
  });
});
```

If I import `SomeComponentHeader` explicitely then this works as expected, but when using auto-import it just renders the full `SomeComponentHeader` inner html.

**Use case:** 
When using tailwind you can catch style changes with snapshot tests.
And you only want to see the styles of the current component under test, so as not to make tests fail when the child element styles update.

For now i'm resorting to simply have the imports in file. but would be nice to figure out why this doesn't work with vitest + [Vue Test Utils](https://test-utils.vuejs.org/) out of the box?

**Comment by JJBocanegra** [comment]
There is no workaround for this yet? 😭

**Comment by Djaler** [comment]
@Neophen that's because `unplugin-vue-components` injects component reference inside render-function, not in `components` option of component. And `vue-test-utils` works by patching `components`

**Comment by wyrd-code** [comment]
Using `vitest` and hitting this same issue. Vitest and `vite` extend the same configuration. I was under the impression that it should just work, both things being vite based?

I'm currently "fixing" it by importing the components like shown below.

```ts
import ComponentA from './ComponentA.vue'
import ComponentB from './ComponentB.vue'

const wrapper = mount(ComponentA, {
  components: {
    ComponentB,
  },
})
```

**Comment by Djaler** [comment]
This fix should allow stubbing autoimported components https://github.com/vuejs/vue-test-utils/pull/2017

**Comment by philly-vanilly** [comment]
I am glad at least some migration tooling like this lib exists but what kind of suggestion is that to "just use cypress"? I have around 1500 unit tests. There is no way I am rewriting them in Cypress.

I appreciate this lib as a temporary solution (too bad tooling like this does not come from the official Vue team), but if I had to use it permanently, I would rather rewrite the frontend in Angular or React than keep using Vue.

@Djaler I am on 1.3.6 and it still does not work
