### ISSUE TITLE
在naive-ui中使用unplugin-vue-components自动引入时NSelect的选项为空

### ISSUE THREAD

**Issue by JawilX** [antfu/unplugin-vue-components#417]
https://github.com/TuSimple/naive-ui/issues/3066

**Comment by yuyinws** [comment]
搭建了一个”最小重现“版本，发现并不能复现你说的问题，可以排查一下是不是其他代码影响到了

[codesandbox](https://codesandbox.io/s/sad-browser-jmlpgk?file=/src/main.ts)
[github](https://github.com/yuyinws/unplugin-vue-components-test)

**Comment by yuyinws** [comment]
TuSimple/naive-ui/issues/3146
是naive-ui的bug 2.3.6版本已修复

**Comment by JawilX** [comment]
@yuyinws 感谢，我没想到是跟关闭options api有关
