### ISSUE TITLE
Vue 组件的报错信息的行号有误

### ISSUE THREAD

**Issue by BryanLi93** [antfu/unplugin-vue-components#421]
`Vite.config.js` 中使用 `Components`，报错信息都提示在 `export default {` 行。注释了 `Components` 则错误提示正常。

版本：vue@_3.2.37_, vite@_2.9.10_, unplugin-vue-components@_0.19.6_

<img width="1037" alt="CleanShot 2022-06-15 at 11 01 55@2x" src="https://user-images.githubusercontent.com/24838088/173727731-73002bb5-a4c2-4cb4-84b7-1aead2b5c0d7.png">

![CleanShot 2022-06-15 at 10 59 06](https://user-images.githubusercontent.com/24838088/173727507-361bc4f4-8fc2-411c-a9d2-a7a0baf12c7e.png)

**Comment by sxzz** [comment]
Duplicate of #219
