### ISSUE TITLE
vuecli下安装运行报错

### ISSUE THREAD

**Issue by weiweishiyi** [antfu/unplugin-vue-components#435]
node_modules/unplugin-vue-components/dist/chunk-MF6CXARB.js:628
                    compiler.watching.invalidate();
                                      ^

TypeError: Cannot read property 'invalidate' of undefined
    at /Users/gaoyan/qwe/yh/node_modules/unplugin-vue-components/dist/chunk-MF6CXARB.js:628:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);

<img width="984" alt="image" src="https://user-images.githubusercontent.com/29918551/175803810-45986cf7-8a90-4353-a40d-d8314f8c5725.png">

**Comment by ChpShy** [comment]
fixed #434
