### ISSUE TITLE
引入依赖直接报错

### ISSUE THREAD

**Issue by kkkklj** [antfu/unplugin-vue-components#453]
node_modules/unplugin/dist/index.js:1021
      setup: ((_a = plugin.esbuild) == null ? void 0 : _a.setup) ?? function setup({ onStart, onEnd, onResolve, onLoad, initialOptions, esbuild: { build: build2 } }) {
                                                                  ^

SyntaxError: Unexpected token '?'

**Comment by kkkklj** [comment]
vite.config.ts中配置的，Components方法调用就报这个错误

**Comment by kkkklj** [comment]
0.19.6并没有这个报错，0.21.1和0.21.0都出现了这个异常

**Comment by suyi91** [comment]
I also had the same problem.
`unplugin@^0.7.0` which is required by `unplugin-vue-components@^0.19.9` has [nullish coalescing operator (??)](https://github.com/tc39/proposal-nullish-coalescing).

> `nullish coalescing operator (??)` needs node 14+ [reference](https://node.green/)

To resolve this problem, we may use node 14 or unplugin-vue-components@ < 0.19.9 .

Perhaps this repo should mention node version compatibility.

----------
也发现了这个语法错误，调查发现是`unplugin-vue-components@^0.19.9`依赖的`unplugin@^0.7.0`用到了node 14才支持的[`??`](https://node.green/)语法。
可以考虑使用<0.19.9的版本，或者用node 14+编译

**Comment by nullhan** [comment]
I also encountered this error,
My version of Node is V12.18.3,

unplugin-vue-components@0.22.7,

I am considering using a version below 0.19.9
