### ISSUE TITLE
关于构建不会生成components.d.ts问题

### ISSUE THREAD

**Issue by mojiefong** [antfu/unplugin-vue-components#462]
因为项目是多人开发，所以把`components.d.ts` 加入到了`.gitignore`。但是构建部署的时候无法生成`components.d.ts` ，就会报错。
如果把`components.d.ts` 也提交的话，那么每人在拉代码的时候都会冲突，时间长了就感觉很恶心了。

我的想法是构建的时候也能生成`components.d.ts`，或者单独加个脚本生成。

请问还有什么好的解决方案吗？谢谢！

**Comment by zhouhuiquan** [comment]
这个文件冲突是个很大的问题, 很多很多冲突.  一开始我们是用git管理了,后面我把这个文件加入了.gitignore文件中, 这样服务器应该也是有的,我们用的Jenkins,没去上面看文件应该还有.  所以没有遇见你说的构建问题.  不过因为我本地的component.d.ts文件里面映射关系不够, 所以在使用了懒加载的情况下, 有些页面不断地触发 new dependencies optimized 和  optimized dependencies changed. reloading  需要很长时间, 也就是说开发模式下 hmr 可能会很慢

**Comment by mojiefong** [comment]
> 这个文件冲突是个很大的问题, 很多很多冲突. 一开始我们是用git管理了,后面我把这个文件加入了.gitignore文件中, 这样服务器应该也是有的,我们用的Jenkins,没去上面看文件应该还有. 所以没有遇见你说的构建问题. 不过因为我本地的component.d.ts文件里面映射关系不够, 所以在使用了懒加载的情况下, 有些页面不断地触发 new dependencies optimized 和 optimized dependencies changed. reloading 需要很长时间, 也就是说开发模式下 hmr 可能会很慢

加入到.gitignore后，把远程的components.d.ts删了，git仓库是没有components.d.ts文件的
然后进入CI流程，npm i && npm build，也就是build是不会生成components.d.ts文件的
你所说的 optimized dependencies changed. reloading 需要很长时间这个问题，把vite升级到2.9以后就不存在了

**Comment by mojiefong** [comment]
> > 这个文件冲突是个很大的问题, 很多很多冲突. 一开始我们是用git管理了,后面我把这个文件加入了.gitignore文件中, 这样服务器应该也是有的,我们用的Jenkins,没去上面看文件应该还有. 所以没有遇见你说的构建问题. 不过因为我本地的component.d.ts文件里面映射关系不够, 所以在使用了懒加载的情况下, 有些页面不断地触发 new dependencies optimized 和 optimized dependencies changed. reloading 需要很长时间, 也就是说开发模式下 hmr 可能会很慢
> 
> 加入到.gitignore后，把远程的components.d.ts删了，git仓库是没有components.d.ts文件的 然后进入CI流程，npm i && npm build，也就是build是不会生成components.d.ts文件的 你所说的 optimized dependencies changed. reloading 需要很长时间这个问题，把vite升级到2.9以后就不存在了

抱歉，我又试了一下，我是把auto-imports.d.ts文件也给加入了.gitignore，在build的时候是auto-imports.d.ts没有生成，components.d.ts生成了😂
看花眼了，我以为是components.d.ts没有生成😂

**Comment by zhouhuiquan** [comment]
我们这个项目没有看到auto-import.d.ts文件。 vite也是2.9.12，reloading还是有有问题， 现在vite.config.ts中加入 optimizeDeps 的include 把 antd-vue的都加进去，当时提示啥加啥，结果是把所有组件的style都加进去了，现在不存在那个一直在reloading的问题，网上有两个插件说可以自动写入这个问题，我试了下没有效果，手动加吧。
最后你的问题是解决了对吧？

**Comment by mojiefong** [comment]
> 我们这个项目没有看到auto-import.d.ts文件。 vite也是2.9.12，reloading还是有有问题， 现在vite.config.ts中加入 optimizeDeps 的include 把 antd-vue的都加进去，当时提示啥加啥，结果是把所有组件的style都加进去了，现在不存在那个一直在reloading的问题，网上有两个插件说可以自动写入这个问题，我试了下没有效果，手动加吧。 最后你的问题是解决了对吧？

是的，解决了，是auto-import.d.ts 文件造成的。
auto-import.d.ts 也是托尼大佬写的一个插件https://github.com/antfu/unplugin-auto-import
我用的element-plus，没有遇到过你说的这种问题
