### ISSUE TITLE
vue component 组件动态注册

### ISSUE THREAD

**Issue by qq1066536** [antfu/unplugin-vue-components#465]
### Clear and concise description of the problem

```vue
<template>
    <el-form
        :ref="formRef"
        :model="form"
        :rules="rules"
        size="small"
        :validate-on-rule-change="false">
        <el-row>
            <el-col v-for="column in columns" v-bind="response" :key="column.prop">
                <el-form-item :label="column.label" :prop="column.prop">
                    <component :is="column.component" />
                </el-form-item>
            </el-col>
        </el-row>
    </el-form>
</template>
<script setup lang='ts'>
import { reactive} from "vue"
const columns = reactive([
    {
        prop: 'userName',
        label: '用户名',
        component: 'el-input',
    },
]);
</script>
```
### Suggested solution

新增includes 属性或者类型于`unplugin-auto-import` 中的imports 属性，自动导入指定的组件

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vfiee** [comment]
Same problem. Hope to fix it soon

**Comment by sxzz** [comment]
Please use https://github.com/antfu/unplugin-auto-import, and do not use string literal `'el-input'`, use `ElInput` variable instead.
