### ISSUE TITLE
<template>中无法使用自动导入的函数

### ISSUE THREAD

**Issue by TaoziDeGitHub** [antfu/unplugin-vue-components#466]
### Describe the bug

<template>中无法使用自动导入的函数

### Reproduction

<template>中无法使用自动导入的函数

### System Info

```Shell
<template>中无法使用自动导入的函数
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
