### ISSUE TITLE
: Cannot read properties of undefined (reading 'invalidate')

### ISSUE THREAD

**Issue by JslinSir** [antfu/unplugin-vue-components#480]
打包报错：npm run build  

` Cannot read properties of undefined (reading 'invalidate')`

- vue cli 项目配置如下：

```
  configureWebpack: {
    devtool: "source-map",
    plugins: [
      ComponentsPlugin({
        resolvers: [VantResolver()],
      }),
    ],
  },
```
- 包版本：  "unplugin-vue-components": "^0.19.6"

**Comment by JslinSir** [comment]
compiler.watching.invalidate();  
 
 Cannot read properties of undefined (reading 'invalidate')

**Comment by ChpShy** [comment]
you can upgrade your version above `v0.20.1`

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
