### ISSUE TITLE
使用unplugin-vue-components自动注册，在<component :is="parameter"></component>无效？

### ISSUE THREAD

**Issue by litchi-lz** [antfu/unplugin-vue-components#482]
### Describe the bug

components.d.ts文件中组件名称与 <component :is="parameter"></component>文件名称一致
` <component :is="detailsArt.parameter"></component>  //无效
          //正常`
`<script setup lang="ts">
const detailsArt = reactive({
  parameter: "WxRequest",
});`
请问是写法有问题还是其他了，哪位大佬知道

### Reproduction

 "unplugin-vue-components": "^0.21.2",   "vite": "^3.0.0",

### System Info

```Shell
"unplugin-vue-components": "^0.21.2",
  "vite": "^3.0.0",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Dulipcate of #11
