### ISSUE TITLE
Error when using Vue2.7 + Webpack5

### ISSUE THREAD

**Issue by tommyriceopen** [antfu/unplugin-vue-components#494]
### Describe the bug

There are 2 export errors when using Vue2.7 + Webpack5

```
export 'render' (imported as 'render') was not found in src/comp/Index.vue
export 'staticRenderFns' (imported as 'staticRenderFns') was not found in src/comp/Index.vue
```

In webpack.config.js, 2 options are included

```
Components({
  dir: ['src/comp']
  transformer: 'vue2',
})
```

These are the versions of the 3 dependencies
```
"dependencies": {
  "webpack": "^5.74.0",
  "vue": "^2.7.7",
  "unplugin-vue-components": "^0.22.4",
}
```

### Reproduction

After installing the packages with the above versions and adding "dir" will cause the error

### System Info

```Shell
Node: 14.17.3
npm: 6.14.13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required
