### ISSUE TITLE
希望可以支持组件名动态设置

### ISSUE THREAD

**Issue by Luin-Li** [antfu/unplugin-vue-components#496]
我们在项目中用了 `antdv` 组件库，但是由于这个组件库有些组件的风格和我们其他项目不太统一，只通过修改主题色等，已经无法满足我们的需求。所以，我们在 `antdv` 的基础上做了一层封装，形成一个和我们组件库风格比较统一的 `xx-antdv` ，并发布到我们私有的npm仓库。
但是这会导致我们无法使用 `unplugin-vue-components`，因为`unplugin-vue-components`的组件名是写死的, 如下，截取部分代码。而我们封装后的组件为了规范，我们是重命名为`xx-ant` 发布到私有的npm仓库的。

```js
if (importStyle === 'less' || importLess) {
    const styleDir = getStyleDir(compName)
    return `ant-design-vue/${lib}/${styleDir}/style`
  }
  else {
    const styleDir = getStyleDir(compName)
    return `ant-design-vue/${lib}/${styleDir}/style/css`
  }
```
是否可以支持组件名动态设置，类似如下，方便在私有的npm仓库对组件进行二次封装这种场景的使用。
```js
{
resolverComponents: 'xx-ant',
}
```

**Comment by azaleta** [comment]
Can't do this?(just a prototype)
```
import {
  AntDesignVueResolver,
} from 'unplugin-vue-components/resolvers'
import type { ComponentInfo, ComponentResolverObject } from 'unplugin-vue-components/types'

const antResolver = AntDesignVueResolver() as ComponentResolverObject
const yourResolver = async (name: string) => {
  const antComponent = await antResolver.resolve(name) as ComponentInfo
  // sample to modify name only(you can modify what you want)
  if (antComponent && antComponent.name)
    antComponent.name = `xx-${antComponent.name}`

  return antComponent
}

...
Components({
      dts: true,
      resolvers: [
        yourResolver,
      ],
 }),
```

**Comment by Luin-Li** [comment]
> 

I changed the ant package's name to 'xx-ant' in the private NPM registry. When I use components without auto importing ,my components path is like `import {Button} from 'xx-ant'`. The AntDesignVueResolver fixed the package's name in the code like `ant-design-vue/${lib}/${styleDir}/style`. A prototype of the resolver can't help.

**Comment by Luin-Li** [comment]
> Can't do this?(just a prototype)
> 
> ```
> import {
>   AntDesignVueResolver,
> } from 'unplugin-vue-components/resolvers'
> import type { ComponentInfo, ComponentResolverObject } from 'unplugin-vue-components/types'
> 
> const antResolver = AntDesignVueResolver() as ComponentResolverObject
> const yourResolver = async (name: string) => {
>   const antComponent = await antResolver.resolve(name) as ComponentInfo
>   // sample to modify name only(you can modify what you want)
>   if (antComponent && antComponent.name)
>     antComponent.name = `xx-${antComponent.name}`
> 
>   return antComponent
> }
> 
> ...
> Components({
>       dts: true,
>       resolvers: [
>         yourResolver,
>       ],
>  }),
> ```

I changed the ant package's name to 'xx-ant' in the private NPM registry. When I use components without auto importing ,my components path is like `import {Button} from 'xx-ant'`. The AntDesignVueResolver fixed the package's name in the code like `ant-design-vue/${lib}/${styleDir}/style`. A prototype of the resolver can't help.

**Comment by azaleta** [comment]
can't get the point.

I suppose you rewrite all components as a private library.
 If you use antResolver you will get a ref object as 
```
{
    name:'Button',
    style: 'ant-design-vue/****/style/css'
    ...
}
```
I think what you want is
```
{
    name:'Button',
    style: 'xx-ant-design-vue/****/style/css'     //  keep the compnent name same as Ant and replace all/some ref file path to your own lib (this is the aim of prototype)
    ...
}
```

am i right? 
if we add 
```
{
resolverComponents: 'xx-ant',
}
```
to config,what result should be outputed?

**Comment by Luin-Li** [comment]
> can't get the point.
> 
> I suppose you rewrite all components as a private library. If you use antResolver you will get a ref object as
> 
> ```
> {
>     name:'Button',
>     style: 'ant-design-vue/****/style/css'
>     ...
> }
> ```
> 
> I think what you want is
> 
> ```
> {
>     name:'Button',
>     style: 'xx-ant-design-vue/****/style/css'     //  keep the compnent name same as Ant and replace all/some ref file path to your own lib (this is the aim of prototype)
>     ...
> }
> ```
> 
> am i right? if we add
> 
> ```
> {
> resolverComponents: 'xx-ant',
> }
> ```
> 
> to config,what result should be outputed?
