### ISSUE TITLE
vite3+vue3+ts全局自动注册，在组件中调用自身时VSCode会报TS7022错误

### ISSUE THREAD

**Issue by Fallsleep** [antfu/unplugin-vue-components#498]
### Describe the bug

全局生成文件配置到了`src/types/components.d.ts`文件时，在`HelloWorld.vue`组件中调用自身时`VSCode`会报TS7022错误，但是页面实际访问时没有任何问题。
实际开发的场景是在`MenuItem`组件的子菜单中嵌套`MenuItem`。
![ts7022](https://user-images.githubusercontent.com/3007987/187167014-db4303a9-e36f-412a-8a0f-410b6453ca7e.png)

这种是bug还是要额外设置忽略特定的文件？

### Reproduction

https://stackblitz.com/edit/vitejs-vite-s1vjfn?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.34 GB / 15.92 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
no error here
![image](https://user-images.githubusercontent.com/22554452/187176532-1ca39c77-a081-4543-ba71-a642cc9b2a57.png)

**Comment by zqy233** [comment]
> no error here ![image](https://user-images.githubusercontent.com/22554452/187176532-1ca39c77-a081-4543-ba71-a642cc9b2a57.png)

请教下，这个显示体积的是什么vscode插件，感谢

**Comment by Fallsleep** [comment]
> no error here ![image](https://user-images.githubusercontent.com/22554452/187176532-1ca39c77-a081-4543-ba71-a642cc9b2a57.png)

我将`Reproduction`中的项目下载到本地后，也出现了你这种情况。于是我和本地的测试项目做了下对比，发现有如下差别：

- 本地项目打开`HelloWorld.vue`时，`VSCode`识别出了项目中的`tsconfig.json`
![Local](https://user-images.githubusercontent.com/3007987/187373530-7b3b06bd-0de1-4831-a39b-b26b4847516d.png)

- `Reproduction`打开`HelloWorld.vue`时，`VSCode`未能识别出了项目中的`tsconfig.json`。但如果点击`TS4.8.2`，将`TypeScript`切换为`VSCode 1.70.2`自带的`4.7.3`，就能识别出`tsconfig.json`，并报错。这时即使切换回`TS4.8.2`，依然会保存。
![Reproduction](https://user-images.githubusercontent.com/3007987/187373718-740324eb-77f2-4bab-8484-fdfb7f7183a7.png)

**Comment by Fallsleep** [comment]
@zqy233  搜了下，似乎是`Import Cost`。

**Comment by zqy233** [comment]
> @zqy233 搜了下，似乎是`Import Cost`。

好的，谢谢

**Comment by Fallsleep** [comment]
今天升级了`volar`扩展，并删除`lock`文件重新安装了依赖，错误提示已经消失。具体由哪些修复了bug尚不能确定。

仅列出删除`lock`文件前手动升级的依赖：
`volar`: 0.40.1 -> 0.40.9

`@vitejs/plugin-legacy`: 2.0.1 -> 2.1.0
`@vitejs/plugin-vue`: 3.0.3 -> 3.1.0
`@vitejs/plugin-vue-jsx`: 2.0.0 -> 2.0.1
`@vue/compiler-sfc`: 3.2.37 -> 3.2.38
`vite`: 3.0.8 -> 3.1.0
`vue-tsc`: 0.40.1 -> 0.40.9

另外[volar扩展](https://marketplace.visualstudio.com/items?itemName=Vue.volar)关于`Recursive components`(即组件递归调用)有额外说明，似乎是3月添加的：
`Bar.vue`
```vue
<template>
  <Bar :a="'wrong'" />
</template>

<script setup lang="ts">
import { defineAsyncComponent, type DefineComponent } from 'vue'

interface Props {
  a: number
}

const Bar = defineAsyncComponent<DefineComponent<Props>>(
  () => import('./Bar.vue') as any
)
defineProps<Props>()
</script>
```
如果后续还会因为递归调用自身报错的话，就可以尝试改为这种形式。
