### ISSUE TITLE
bug: HeadlessUiResolver not generating types for components

### ISSUE THREAD

**Issue by Async0x42** [antfu/unplugin-vue-components#50]
vite.config.ts
```
customComponentResolvers: [
  HeadlessUiResolver()
]
```

is not generating types for the Headless UI components as expected. When I remove ``` import { Listbox, ListboxButton, ListboxLabel, ListboxOption, ListboxOptions } from '@headlessui/vue'; ``` then the components have no typings in the template.

**Comment by antfu** [comment]
Can you reverify with the latest version? Thanks.
