### ISSUE TITLE
ElementPlusResolver自动生成的components.d.ts文件和auto-imports.d.ts时不完全，只生成了部分。

### ISSUE THREAD

**Issue by ll60** [antfu/unplugin-vue-components#502]
### Describe the bug

在启动项目时，重新生成的components.d.ts文件和auto-imports.d.ts不完整，只有当页面访问到某个指定页面的时候，文件才会更新完整。

### Reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
The plugin doesn't know which components you're using when it's not yet loaded. It is recommended to execute `vite build` at the beginning.

还没访问的时候，插件并不知道你用了哪些组件。建议在一开始使用 `vite build` 跑一遍。

**Comment by ll60** [comment]
> The plugin doesn't know which components you're using when it's not yet loaded. It is recommended to execute `vite build` at the beginning.
> 
> 还没访问的时候，插件并不知道你用了哪些组件。建议在一开始使用 `vite build` 跑一遍。

可，如果一开始build的话，ts会检查类型,之后报找不到名称XX。例: Cannot find name 'ElMessage'

**Comment by sxzz** [comment]
把 dts 提交到 git

**Comment by ll60** [comment]
> 
目前的解决方法的话，我只能把更改撤回是吗。

**Comment by sxzz** [comment]
开发的时候把生成好了的 dts 提交到 git 仓库。那么在构建的时候，就不需要生成了。

**Comment by ll60** [comment]
> 开发的时候把生成好了的 dts 提交到 git 仓库。那么在构建的时候，就不需要生成了。

嗯，现在就是这么做的了。没有更好的方法了。
