### ISSUE TITLE
It is normal during debugging, but cannot be recognized after packaging

### ISSUE THREAD

**Issue by PZD2937** [antfu/unplugin-vue-components#504]
### Describe the bug

![image](https://user-images.githubusercontent.com/50706050/188054588-ff296d03-a56e-422e-97eb-566ae8722f07.png)

![image](https://user-images.githubusercontent.com/50706050/188064127-785228d4-f0d5-499f-9a0a-71f90a913d4d.png)

use
![image](https://user-images.githubusercontent.com/50706050/188064266-3b032e85-59e9-4a81-ba74-e54a77becfb1.png)

### Reproduction

*

### System Info

```Shell
System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 3.75 GB / 15.95 GB
  Binaries:
    Node: 16.14.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.0 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PZD2937** [comment]
此页面只使用了el-input 和 v-infinite-scroll

**Comment by PZD2937** [comment]
其他使用element组件的页面都能正常使用

**Comment by sxzz** [comment]
![image](https://user-images.githubusercontent.com/6481596/188590174-db6d643d-7a8b-4571-90e4-96183f6a506f.png)
https://antfu.me/posts/why-reproductions-are-required-zh
