### ISSUE TITLE
无法进行debugger 和google 断点调试

### ISSUE THREAD

**Issue by zhoulangchua** [antfu/unplugin-vue-components#506]
### Describe the bug

使用的框架 vue3+vite  

使用      "unplugin-vue-components"  当前最新0.22.4 版本无法进行debugger 和google 调试了 
![image](https://user-images.githubusercontent.com/29749443/188114181-74e9d17d-506d-4e44-bfaa-a798cf7d10ce.png)

不进入我的 setup函数
![464ce11f8490f1fb5d665a0b519e601](https://user-images.githubusercontent.com/29749443/188114252-80fc088d-90b7-42a6-ab5a-514f2b3dcadf.jpg)

去掉此插件正常使用

![image](https://user-images.githubusercontent.com/29749443/188115173-35cd1853-799a-46e8-9a62-c70432fe179f.png)
以上是我的vite.config.js 中的引用

### Reproduction

开发环境

### System Info

```Shell
Google Chrome
版本 104.0.5112.102（正式版本） （64 位）
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by favorite58** [comment]
这个问题有计划解决吗？我也遇到这bug了，配置后子组件无法断点

**Comment by azaleta** [comment]
seems fine.
![image](https://user-images.githubusercontent.com/22554452/188549972-553b7605-aea6-4015-b9b2-0f44adff0e45.png)

![image](https://user-images.githubusercontent.com/22554452/188549917-9359381b-c4d7-4588-a3c3-d45a418c530c.png)

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
