### ISSUE TITLE
Enabling directives in Vue 2.7 project not working

### ISSUE THREAD

**Issue by sconix** [antfu/unplugin-vue-components#517]
### Describe the bug

Enabling directives loading in Vue 2.7 project using Vite will cause the following error:

[vite] Internal server error: [unplugin-vue-components:directive] Cannot find render function position.

Noticed that it works correctly if I revert the change to getRenderFnStart function call location made by the following PR:
https://github.com/antfu/unplugin-vue-components/pull/487

### Reproduction

https://stackblitz.com/edit/vitejs-vite-mg4vpj?file=README.md

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 29.59 GB / 29.60 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://github.com/antfu/unplugin-vue-components/pull/487/files#diff-5fd8545fca1393ecb89b463c9ebddccad293df3a0d3bf519a95bdaedabbff407L61

@sxzz 
Look like moving this line causes this problem.

The App.vue(style part) will be processed by `transformDirectives`

```
import { updateStyle as __vite__updateStyle, removeStyle as __vite__removeStyle } from "/@vite/client"
const __vite__id = "C:/Users/208523672/Desktop/ts/src/App.vue?vue&type=style&index=0&scoped=7a7a37b1&lang.scss"
const __vite__css = ".bg[data-v-7a7a37b1] {\n  background: #f8f8fb;\n  height: 100%;\n}"
__vite__updateStyle(__vite__id, __vite__css)
import.meta.hot.accept()
export default __vite__css
import.meta.hot.prune(() => __vite__removeStyle(__vite__id))
```

Code like this, `getRenderFnStart` will throw error.

**Comment by sconix** [comment]
Thanks for the quick fix, any change to get a new release so we can get CI automation working again?
