### ISSUE TITLE
Vue 2.7 generated components.d.ts has unecessary spaces, causing lint / prettier problems

### ISSUE THREAD

**Issue by cadriel** [antfu/unplugin-vue-components#532]
### Describe the bug

The auto-generated `components.d.ts` has formatting issues;

```ts
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}
        
declare module 'vue' {...
```

Note the additional spaces after the export line. This causes linting issues, especially with prettier formatting enabled (the default rules for a new vue 2 project..)

### Reproduction

Create a new Vue 2 project using npm create, and install unplugin-vue-components

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 32.14 GB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.1 - ~/.n/bin/node
    npm: 8.15.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed via #533
