### ISSUE TITLE
二次封装组件怎么jsx，样式无法被导入

### ISSUE THREAD

**Issue by luocong2016** [antfu/unplugin-vue-components#542]
### Clear and concise description of the problem

1. 在一个ui库上进行封装，如：vant ；然后把这个库打包且排除 “vant”
```jsx
export default defineComponent({
 name: 'CButton'
 setup() {
   return () => <van-button>xxx</van-button>
 }
})
```

2. 使用
```
<c-button>xxx<c-button>
```

3. 并没有导入
```
import 'vant/es/button'
```

被编译成如下，可能还是jsx 原因吧。有没有办法解决

```
import { Button } from "vant";
_createVNode(Button, ...)
```

### Suggested solution

能不能选择 node_modules里面呢， 我尝试了 include 正则。但并没有效果

### Alternative

unknow

### Additional context

unset

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Please use `unplugin-auto-import` for JSX.

**Comment by luocong2016** [comment]
感谢回复，那个样式没导入，是不是 resolvers 自定义
