### ISSUE TITLE
`collapseSamePrefixes` option does not work

### ISSUE THREAD

**Issue by hymair** [antfu/unplugin-vue-components#546]
### Describe the bug

As you can see in the repro, `components/app/sidebar/Sidebar` is not registered as `AppSidebar`, but as `AppSidebarSidebar`.

Related to this PR: https://github.com/antfu/unplugin-vue-components/pull/409

### Reproduction

https://stackblitz.com/edit/vitejs-vite-2s7kwu

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.14 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DrJume** [comment]
Thank you! I found the probable cause of this issue and will raise a PR shortly.

**Comment by DrJume** [comment]
Sorry for the delay, happened to be a bit more than a typo, as I initially thought...
