### ISSUE TITLE
DirectoryAsNamespace doesnt work

### ISSUE THREAD

**Issue by Rasool-deldar** [antfu/unplugin-vue-components#548]
### Describe the bug

I set DirectoryAsNamespace to true, but it doesn't work
I want to have the following output
components/Au/HelloWorld.vue --> AuHelloWorld
But it gives me the following output
components/Au/HelloWorld.vue --> HelloWorld
Please solve this problem

Also, the Index.vue section inside the Au folder has a problem and it does not load. Please solve this issue as well.

### Reproduction

https://codesandbox.io/s/gracious-newton-fx2nmo?file=/vite.config.ts:1002-1022

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 18.68 GB / 31.91 GB
  Binaries:
    Node: 18.8.0 - C:\Dev\Web\laragon\bin\nodejs\node-v18\node.EXE
    Yarn: 1.22.19 - C:\Dev\Web\laragon\bin\nodejs\node-v18\yarn.CMD
    npm: 8.18.0 - C:\Dev\Web\laragon\bin\nodejs\node-v18\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
just change your config
```
dirs: ["src/components/**"], -> dirs: ["src/components"],
```

**Comment by Rasool-deldar** [comment]
> 

Thanks, solved
