### ISSUE TITLE
ERROR  [vite]: Rollup failed to resolve import

### ISSUE THREAD

**Issue by Verdicts-ye** [antfu/unplugin-vue-components#549]
### Describe the bug

ERROR  [vite]: Rollup failed to resolve import "@vant/use" from "node_modules/vant/es/action-bar-button/ActionBarButton.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
[uni-preset-vue-vite-ts.zip](https://github.com/antfu/unplugin-vue-components/files/9976583/uni-preset-vue-vite-ts.zip)

### Reproduction

Please see the upload attachment

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7810HQ CPU @ 1.60GHz
    Memory: 19.28 GB / 31.95 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by i7eo** [comment]
请问这个解决了吗？

**Comment by i7eo** [comment]
> ### Describe the bug
> ERROR [vite]: Rollup failed to resolve import "@vant/use" from "node_modules/vant/es/action-bar-button/ActionBarButton.mjs". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to `build.rollupOptions.external` [uni-preset-vue-vite-ts.zip](https://github.com/antfu/unplugin-vue-components/files/9976583/uni-preset-vue-vite-ts.zip)
> 
> ### Reproduction
> Please see the upload attachment
> 
> ### System Info
> ```shell
> System:
>     OS: Windows 10 10.0.19044
>     CPU: (8) x64 Intel(R) Core(TM) i7-7810HQ CPU @ 1.60GHz
>     Memory: 19.28 GB / 31.95 GB
>   Binaries:
>     Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
>     npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: Spartan (44.19041.1266.0)
>     Internet Explorer: 11.0.19041.1566
> ```
> 
> ### Used Package Manager
> pnpm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/antfu/contribute).
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

请问这个解决了吗？

**Comment by Verdicts-ye** [comment]
没，vant不支持uniapp






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antfu/unplugin-vue-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月21日(星期三) 晚上6:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [antfu/unplugin-vue-components] ERROR  [vite]: Rollup failed to resolve import (Issue #549)





  
Describe the bug
 
ERROR [vite]: Rollup failed to resolve import ***@***.***/use" from "node_modules/vant/es/action-bar-button/ActionBarButton.mjs". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to build.rollupOptions.external uni-preset-vue-vite-ts.zip
 
Reproduction
 
Please see the upload attachment
 
System Info
 System:     OS: Windows 10 10.0.19044     CPU: (8) x64 Intel(R) Core(TM) i7-7810HQ CPU @ 1.60GHz     Memory: 19.28 GB / 31.95 GB   Binaries:     Node: 16.13.1 - C:\Program Files\nodejs\node.EXE     npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: Spartan (44.19041.1266.0)     Internet Explorer: 11.0.19041.1566
 
Used Package Manager
 
pnpm
 
Validations
  
  Follow our Code of Conduct
 
  Read the Contributing Guide.
 
  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
 
  Check that this is a concrete bug. For Q&amp;A, please open a GitHub Discussion instead.
 
  The provided reproduction is a minimal reproducible of the bug.
   
请问这个解决了吗？
