### ISSUE TITLE
Uses like <component is="xxx" /> are not supported

### ISSUE THREAD

**Issue by GOGOGOSIR** [antfu/unplugin-vue-components#556]
### Describe the bug

![image](https://user-images.githubusercontent.com/26272801/203466076-84dfb378-d85b-4ce3-8c78-679cf1579bf8.png)
![image](https://user-images.githubusercontent.com/26272801/203466092-b051ad3a-8690-447c-8ae4-2aff53ec0080.png)

### Reproduction

https://github.com/GOGOGOSIR/auto-component-issue.git

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.19.2 - ~/Library/pnpm/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 99.0.4844.84
    Firefox: 96.0.2
    Safari: 13.1.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by trry-github** [comment]
Have you solved it?

**Comment by set0x** [comment]
I have the same problem, any solution?

**Comment by supuwoerc** [comment]
+1 @antfu

**Comment by supuwoerc** [comment]
> I have the same problem, temporary solution with `defineAsyncComponent`
> 
> ```
> <Component :is="defineAsyncComponent(() => import(`@/components/${component}.vue`))" />
> ```

This is still a problem when the component is a third party ui
