### ISSUE TITLE
无法解析VanTabbarItem组件

### ISSUE THREAD

**Issue by Swordder** [antfu/unplugin-vue-components#571]
### Describe the bug

我可以使用vant其他组件，但是在使用vanTabbarItem组件报错
<img width="893" alt="image" src="https://user-images.githubusercontent.com/60690049/209783469-fbbea359-2290-4bf9-8d36-a8d44d938896.png">
dts开了，组件已声明，但是就是没法用，不晓得这个问题原因，求解

### Reproduction

install => configure in vite.config.js(use vantresolver()) => bootstrap => error

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 32.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
need reproduction
