### ISSUE TITLE
jenkins 构建时 src/components组件丢失

### ISSUE THREAD

**Issue by NeAwqz** [antfu/unplugin-vue-components#594]
### Describe the bug

本地或者是在一台centos 上 执行npm run build 命令，是正常的。但是走jenkins构建时，自动生成的 components.d.ts 文件会丢失 src/compnents下的组件，也没能最终打包到dist里。

vite.config.ts是这样配置的 
 ````ts
plugins: [
      vue(),
      viteCommonjs(),
      AutoImport({ 
        imports: ['vue', 'vue-router', 'pinia'], 
        dts: "src/auto-imports.d.ts", 
        resolvers: [ 
          ElementPlusResolver(),
        ], 
      }),
      Components({
        dts: 'src/components.d.ts', 
        resolvers: [ 
          ElementPlusResolver(),
        ],
        extensions: ['vue', 'ts', 'md'],
        include: [/\.vue$/, /\.vue\?vue/, /\.md$/],  
      }),
    ]
````

### Reproduction

jenkins 构建

### System Info

```Shell
node版本：v16.18.1
npm版本：8.19.2
vite版本：3.2.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chengpeiquan** [comment]
之前我在 #220 提过 Jenkins 的问题，不过后来发现是运维的配置问题。

最开始他把 workspace 是用中文括号命名，比如 `project_name（测试服）` ，他以为 workspace 的名字只是一个读取标识，其实打包的时候好像影响了文件的路径读取，后来改成真实的文件夹名称 `project_name_dev` ，确保路径能正确指向文件就可以了，不知道你们是不是一样的情况。

**Comment by NeAwqz** [comment]
@chengpeiquan 我之前有尝试过您说的解决方案，但是并不起作用。┭┮﹏┭┮

**Comment by NeAwqz** [comment]
@chengpeiquan 不好意思，我今天才发现是不能加括号，而不是仅限于不能加中文括号。问题终于解决了，非常感谢您的建议！！！

**Comment by qZhiKing** [comment]
<img width="434" height="63" alt="Image" src="https://github.com/user-attachments/assets/97b01f84-2370-496d-8a69-0ced8a6ec991" />
我想问下是这个地方不能加括号吗

**Comment by qZhiKing** [comment]
> <img alt="Image" width="434" height="63" src="https://private-user-images.githubusercontent.com/76581132/522299950-97b01f84-2370-496d-8a69-0ced8a6ec991.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ4MzUxMDksIm5iZiI6MTc2NDgzNDgwOSwicGF0aCI6Ii83NjU4MTEzMi81MjIyOTk5NTAtOTdiMDFmODQtMjM3MC00OTZkLThhNjktMGNlZDhhNmVjOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA0VDA3NTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwODlhZjZlOWJlMmYyNmNhMjgxN2FiODE0MmJjZWFiNjk4ZGQwYjI0ZTNkYzRmM2QyOWRiNmRlN2NkOWU1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A8-hUz_9WMGtZZ7Ui98ChoHgG0dQutRHcXrw6Z_2Hn4"> 我想问下是这个地方不能加括号吗

是的，将(dev)删除后，就能够解决问题了
