### ISSUE TITLE
Do we support .tsx files as components in VitePress ?

### ISSUE THREAD

**Issue by zack-xy** [antfu/unplugin-vue-components#598]
**Describe the bug:** 

 I have two files in  `.vitepress/theme/components`  folder,  `VueCom.vue` and `TsxCom.tsx`.

 `<VueCom />` can be rendered in markdown file while `<TsxCom />` is not.

I want the .tsx file also can be rendered in .md file . Do we support this ?

**Reproduction:** https://github.com/zack-xy/try-projects/tree/main/vitepress-starter

**System Info**：  

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 57.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm

Browsers:
    Chrome: 110.0.5481.77
    Safari: 16.1

**Used Package Manager**：pnpm@7.18.0

And here is the `vite.config.ts`

``` typescript
import { defineConfig } from 'vite'
import Components from 'unplugin-vue-components/vite'
import vueJsx from '@vitejs/plugin-vue-jsx'
export default defineConfig({
  plugins: [
     Components({
       dirs: ['.vitepress/theme/components'],
       include: [/\.vue$/, /\.vue\?vue/, /\.md$/, /\.tsx/, /\.jsx/],
       resolvers: [],
     }),
    vueJsx(),
  ],
})
```

**Comment by lishaobos** [comment]
hi, take this

```js
Components({
      dirs: ['.vitepress/theme/components'],
      extensions: ['vue', 'tsx'], // this line
      include: [/\.vue$/, /\.vue\?vue/, /\.md$/, /\.tsx/, /\.jsx/],
      resolvers: [
      ],
})
```

![image](https://user-images.githubusercontent.com/46661044/220254391-a5dc9218-28f4-44f9-a8a3-e34ab5eae96f.png)

**Comment by zack-xy** [comment]
It works! Thanks a lot for your help!

**Comment by lishaobos** [comment]
> It works! Thanks a lot for your help!

u are wellcome.

**Comment by icemanjin** [comment]
It works! Thanks a lot for your help!
