### ISSUE TITLE
Recursive components do not work without naming the component

### ISSUE THREAD

**Issue by Napzu** [antfu/unplugin-vue-components#60]
I have a recursive component that uses itself. The root component is auto imported and works, but calling the same component from the component wont.

But if you name the component, then it works.

Example:
```html
<template>
    <div>
        <my-comp v-if="!level" :level="level+1"/>
    </div>
</template>

<script>
// src/components/my-comp.vue
export default {
    //name: 'my-comp', // COMPONENT RECURSION DO NOT WORK WITHOUT THIS LINE
    props: {
        level : { default: 0 }
    }
}
</script>
```

**Comment by Akryum** [comment]
https://vuejs.org/v2/api/#name

> Allow the component to recursively invoke itself in its template.
