### ISSUE TITLE
Addition of hard dependency on Nuxt adds 100+ additional dependencies

### ISSUE THREAD

**Issue by ascott18** [antfu/unplugin-vue-components#606]
### Describe the bug

The new dependency on @nuxt/kit in 0.23 added an additional 108 dependencies to this package.

In 0.22.12, when I add this package to my project it brings in 18 dependencies.
In 0.23.0+, when I add this package to my project it brings in 126 dependencies.

It would be much appreciated if this could be changed to an optional peer dependency instead of a hard dependency. Thank you!

### Reproduction

`npm i unplugin-vue-components@latest -D`, observe output

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.80 GB / 15.71 GB
  Binaries:
    Node: 18.14.2 - ~\Desktop\node-v18.14.2-win-x64\node.EXE
    npm: 9.5.0 - ~\Desktop\node-v18.14.2-win-x64\npm.CMD
  Browsers:
    Chrome: 110.0.5481.177
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stratdev3** [comment]
same observations, the nuxt/kit hard dependancie is overkill.
