### ISSUE TITLE
[Bug]Can't not get right type for vue component prop

### ISSUE THREAD

**Issue by ishowman** [antfu/unplugin-vue-components#635]
### Describe the bug

When I do not install `unplugin-vue-components`:
- volar could know that `msg` prop should be string but not number;
![image](https://github.com/antfu/unplugin-vue-components/assets/16897283/46e85b46-e8f7-4f67-a7fa-f3d8fe80a3c5)
- `pnpm build` could get the same error type info

After install `unplugin-vue-components`, and add comment for import statement:
- the error disappear, and volar tells me  `msg` prop is number
![image](https://github.com/antfu/unplugin-vue-components/assets/16897283/95137aee-329a-4216-afb2-de701c8122cc)
- `pnpm build` succeed and no error info
- If I remove comment for import statement, it behaves as screenshot1 even `component.d.ts` still declare `HelloWorld` component
> `HelloWorld.vue` is created by `create vue`, I didn't change any codes.

**I am not sure the bug is caused by `unplugin-vue-components` or `vue-tsc`, please check it**.

# how i create the repo
- init with  `create-vue`  to create project
- install `unplugin-auto-import`, here is the [code diff](https://github.com/ishowman/vue3-ts-buiild-bug/pull/2)
- install `unplugin-vue-components`, here is the [code diff](https://github.com/ishowman/vue3-ts-buiild-bug/pull/1/files))

### Reproduction

https://github.com/ishowman/vue3-ts-buiild-bug/tree/vue-components

### System Info

**Plugins**: (already finish setup with [volar-takeover-mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode))
- Vue Language Features (Volar)：v1.6.4
- TypeScript Vue Plugin (Volar)：v1.6.5

```Shell
pnpm: 8.5.1
node: 18.12.1


 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.97 GB / 7.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ishowman** [comment]
@antfu   I am not sure the bug is caused by `unplugin-vue-components` or `vue-tsc`, could you do me a favour?

**Comment by lishaobos** [comment]
hi, just put your components.d.ts in src directory

```js
Components({
      dts: './src/components.d.ts'
    })
```


![image](https://github.com/antfu/unplugin-vue-components/assets/46661044/24f443a0-fec5-4f3c-8817-57fb09a33f37)

**Comment by ishowman** [comment]
> 



> hi, just put your components.d.ts in src directory
> 
> ```js
> Components({
>       dts: './src/components.d.ts'
>     })
> ```
> 
> ![image](https://user-images.githubusercontent.com/46661044/240149734-24f443a0-fec5-4f3c-8817-57fb09a33f37.png)

I've move the file and change the file path in tsconfig.app.json, and choose `Volar: restart vue server`：
![image](https://github.com/antfu/unplugin-vue-components/assets/16897283/b24ac8da-c7de-4552-b6d5-22be00c6e7b2)

![image](https://github.com/antfu/unplugin-vue-components/assets/16897283/01275e41-dcce-4ff4-8144-46dbd091dce0)

Still not work
![image](https://github.com/antfu/unplugin-vue-components/assets/16897283/a38d9cee-b4f8-488d-9eed-641944361e3f)

**Comment by lishaobos** [comment]
your pkg manager is npm or pnpm

**Comment by lishaobos** [comment]
> > your pkg manager is npm or pnpm
> 
> pnpm

exec pnpm add @vue/runtime-core -D

and restart your ide

**Comment by lishaobos** [comment]
i think is pnpm bug or limit

**Comment by ishowman** [comment]
> i think is pnpm bug or limit

If install dependencies with npm or yarn, it will work normally without `pnpm add @vue/runtime-core -D`?

**Comment by lishaobos** [comment]
> If install dependencies with npm or yarn, it will work normally without `pnpm add @vue/runtime-core -D`?

looks like it.

**Comment by ishowman** [comment]
> > > your pkg manager is npm or pnpm
> > 
> > 
> > pnpm
> 
> exec pnpm add @vue/runtime-core -D
> 
> and restart your ide

If I make type check in ci ,and ci do not have any ide to reload,what should I do?

**Comment by lishaobos** [comment]
> > > > your pkg manager is npm or pnpm
> > > 
> > > 
> > > pnpm
> > 
> > 
> > exec pnpm add @vue/runtime-core -D
> > and restart your ide
> 
> If I build project in ci ,and ci do not have any ide to reload,what should I do?

ci do not need to reload.

**Comment by ishowman** [comment]
> > > > > your pkg manager is npm or pnpm
> > > > 
> > > > 
> > > > pnpm
> > > 
> > > 
> > > exec pnpm add @vue/runtime-core -D
> > > and restart your ide
> > 
> > 
> > If I build project in ci ,and ci do not have any ide to reload,what should I do?
> 
> ci do not need

> > > > > your pkg manager is npm or pnpm
> > > > 
> > > > 
> > > > pnpm
> > > 
> > > 
> > > exec pnpm add @vue/runtime-core -D
> > > and restart your ide
> > 
> > 
> > If I build project in ci ,and ci do not have any ide to reload,what should I do?
> 
> ci do not need to reload.

ci can't find type error in this case, and will pass when run npm scripts `build`.

**Comment by daiwanxing** [comment]
> > > your pkg manager is npm or pnpm
> > 
> > 
> > pnpm
> 
> exec pnpm add @vue/runtime-core -D
> 
> and restart your ide

This method solved my problem,  It's weired. 
I open the `components.d.ts` file and found the first line declare:
```ts
import '@vue/runtime-core
```
If we don't install that package. I guess The `d.ts` file will be slient load error and result in load component type failed ?

**Comment by ishowman** [comment]
> 

will it not work in ci for there is no vscode in ci? I am confuse about why  restar vscode is necessary, while ci need to run `build `script to check types.

**Comment by lishaobos** [comment]
> > 
> 
> will it not work in ci for there is no vscode in ci? I am confuse about why restar vscode is necessary, while ci need to run `build `script to check types.它会在 CI 中不起作用，因为 CI 中没有 VScode？我对为什么需要重新命名 vscode 感到困惑，而 ci 需要运行 `build ` 脚本来检查类型。

because need trigger syntax highlighting on vscode, nothing else.

**Comment by ishowman** [comment]
> > > 
> > 
> > 
> > will it not work in ci for there is no vscode in ci? I am confuse about why restar vscode is necessary, while ci need to run `build `script to check types.它会在 CI 中不起作用，因为 CI 中没有 VScode？我对为什么需要重新命名 vscode 感到困惑，而 ci 需要运行 `build ` 脚本来检查类型。
> 
> because need trigger syntax highlighting on vscode, nothing else.

so the type-checking of vue-tsc will work normally if no vscode reload, right?

**Comment by lishaobos** [comment]
> > > > 
> > > 
> > > 
> > > will it not work in ci for there is no vscode in ci? I am confuse about why restar vscode is necessary, while ci need to run `build `script to check types.它会在 CI 中不起作用，因为 CI 中没有 VScode？我对为什么需要重新命名 vscode 感到困惑，而 ci 需要运行 `build ` 脚本来检查类型。
> > 
> > 
> > because need trigger syntax highlighting on vscode, nothing else.
> 
> so the type-checking of vue-tsc will work normally if no vscode reload, right?

yes, 😎

**Comment by richex-cn** [comment]
I got similar problem and resolved it with https://github.com/antfu/unplugin-vue-components/issues/635#issuecomment-1560678975

![](https://github.com/antfu/unplugin-vue-components/assets/25103518/bb3fe075-d76b-49de-92ea-65ec8377d612)

**Comment by wenfangdu** [comment]
Will be fixed by https://github.com/antfu/unplugin-vue-components/pull/638.
