### ISSUE TITLE
[Resolved] Typescript 5.1 has broken this plugin.(Volar needs to be updated to version 1.7.12 and above)

### ISSUE THREAD

**Issue by lvzhenbo** [antfu/unplugin-vue-components#641]
### Describe the bug

Today, I updated VSC to 1.79. As I am using the built-in version of TS for VSC, version 5.1.3, I found that the TS type inference of the plugin is invalid.
Then when I switched to TS with built-in version 5.0.4 of the project, everything returned to normal
v5.1.3
![image](https://github.com/antfu/unplugin-vue-components/assets/32427677/b9fb4006-434a-45b8-8b5b-d4898de2fa66)
v5.0.4
![image](https://github.com/antfu/unplugin-vue-components/assets/32427677/b0bf17a1-c682-4dd0-b817-982ef22adc9d)

### Reproduction

https://github.com/lvzhenbo/legado-web

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.32 GB / 7.91 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1778.0), Chromium (114.0.1823.41)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ywenhao** [comment]
![image](https://github.com/antfu/unplugin-vue-components/assets/37856060/83483692-5599-4469-9ee8-7fe9b327f870)
![image](https://github.com/antfu/unplugin-vue-components/assets/37856060/019a7dda-6297-4c80-825e-3a2252dacd13)

**Comment by TrueNine** [comment]
same issue

**Comment by gustavotoyota** [comment]
Same here, changing Typescript to 4.8.3 solved for me.

**Comment by JaavierR** [comment]
> ![image](https://user-images.githubusercontent.com/37856060/244602981-83483692-5599-4469-9ee8-7fe9b327f870.png) ![image](https://user-images.githubusercontent.com/37856060/244603032-019a7dda-6297-4c80-825e-3a2252dacd13.png)

Im facing the same issue here, but if I do what the image shows above it works again in typescript 5.1.3.

**Comment by ywenhao** [comment]
you can change the vscode typescript 5.0.4
![image](https://github.com/antfu/unplugin-vue-components/assets/37856060/cfb7054e-3855-46fc-b573-9cff8a057477)
![image](https://github.com/antfu/unplugin-vue-components/assets/37856060/e11aeac3-fd6f-492e-bf1d-decc40cea2e9)

**Comment by manmen-mi** [comment]
It looks `Vue Language Features (Volar)` extension's problem, see https://github.com/vuejs/language-tools/pull/3277 .
(and extention has been updated today)

**Comment by lvzhenbo** [comment]
> It looks `Vue Language Features (Volar)` extension's problem, see [vuejs/language-tools#3277](https://github.com/vuejs/language-tools/pull/3277) . (and extention has been updated today)

After testing, it is indeed volar's ts compatibility problem, but the version has not been officially released, need to switch to the pre-release version
![image](https://github.com/antfu/unplugin-vue-components/assets/32427677/4d406673-d6a5-4801-af75-16d837bd8a2c)

**Comment by so1ve** [comment]
If this problem has been resolved, p least close this issue 😄
