### ISSUE TITLE
feature proposal:  make <component :is='xx'  work

### ISSUE THREAD

**Issue by lishaobos** [antfu/unplugin-vue-components#643]
### Clear and concise description of the problem

<component :is='xx'  is not  work.

### Suggested solution

user can provide some comments:

```html
/* unplugin-vue-components ['name1', 'name2'] */
```

or we can provide API like this:

```js
defineUnpluginComponents(
    ['name1', 'name2']
)
```

and then we auto imported name1,name2 

before
```js
(_openBlock(), _createBlock(_resolveDynamicComponent("name1")))
```

after
```js
import name1 from 'xx'
import name2 from 'xx'

const _getUnpluginDynamicComponent = name => {
  const _unpluginDynamicComponent = {
      name1,
      name2
  }

  return _unpluginDynamicComponent[name] || name
}


// we can replace the _resolveDynamicComponent
(_openBlock(), _createBlock(_resolveDynamicComponent(_getUnpluginDynamicComponent("name1"))))


// or we can inject components
defineCompoennt({
  components: { name1, name2  },
  setup() {
  // ...
  }
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https:github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate### Clear and concise

**Comment by lishaobos** [comment]
@antfu need some advice.

**Comment by antfu** [comment]
Thanks, but no. This is considered out of scope. If you need to do that, I'd suggest importing components explicitly or registering them as global components.

**Comment by lishaobos** [comment]
ok, i got it

**Comment by MrXiaoChuan** [comment]
要想使用<component :is='xx'，只能全局注册，就导致我都全局注册了组件库，为啥要用unplugin-vue-components插件
