### ISSUE TITLE
在hooks里调用组件失效，显示组件未注册

### ISSUE THREAD

**Issue by guohuihot** [antfu/unplugin-vue-components#647]
### Describe the bug

这是最小实现，我不知道在这里提问对不对？也可能是unplugin-auto-import的问题
https://gitee.com/guohuihot/vue2.7_demo
![image](https://github.com/antfu/unplugin-vue-components/assets/3119995/60c05e31-67ba-45a0-8fd9-0433203df9dd)

### Reproduction

https://gitee.com/guohuihot/vue2.7_demo

### System Info

```Shell
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 6.68 GB / 11.92 GB
  Binaries:
    Node: 18.16.0
    Yarn: 1.22.17
    npm: 9.5.1
  Browsers:
    Edge: Spartan (44.18362.387.0)
    Internet Explorer: 11.0.18362.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by guohuihot** [comment]
@antfu

**Comment by antfu** [comment]
This plugin only works for template and have no plan to support JSX.

**Comment by guohuihot** [comment]
> This plugin only works for template and have no plan to support JSX.

好吧，谢谢老板的回复

**Comment by guohuihot** [comment]
加上下面配置可以了，记录下
```
            include: [
              /\.vue$/,
              /\.vue\?vue/,
              /\.js$/,
            ],
```

**Comment by gow1080p** [comment]
> 加上下面配置可以了，记录下
> 
> ```
>             include: [
>               /\.vue$/,
>               /\.vue\?vue/,
>               /\.js$/,
>             ],
> ```

请教下你怎么在js里写jsx的

**Comment by guohuihot** [comment]
> > 加上下面配置可以了，记录下
> > ```
> >             include: [
> >               /\.vue$/,
> >               /\.vue\?vue/,
> >               /\.js$/,
> >             ],
> > ```
> 
> 请教下你怎么在js里写jsx的

`@vue/babel-preset-jsx` 装这个插件
