### ISSUE TITLE
自定义dirs, 是全量引入而不是按需引入

### ISSUE THREAD

**Issue by wc19950724** [antfu/unplugin-vue-components#655]
### Describe the bug

```js
import Components from 'unplugin-vue-components/vite';
export default defineConfig(() => {
    plugins: [
        Components({
            // 子项目自身组件 & monorepo公共组件
            dirs: ['src/components', '../../src/components'],
            resolvers: [TDesignResolver({
                library: 'vue-next',
            })],
        }),
    ]
})
```

### Reproduction

none

### System Info

```Shell
chrome
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
你好，请问，是全量引入是根据什么发现的呢

**Comment by wc19950724** [comment]
> 你好，请问，是全量引入是根据什么发现的呢

情况1: 如果我不配置dirs，则组件均需访问对应页面才会生成，配置之后启动项目则全部生成
情况2: 配置了`../../src/components` , 项目中没用到的组件也全部生成了

**Comment by lishaobos** [comment]
你这个 demo 中，意思是 TestAuto 没有使用，但是 dts 生成了吗

**Comment by wc19950724** [comment]
> 你这个 demo 中，意思是 TestAuto 没有使用，但是 dts 生成了吗

是的！

**Comment by lishaobos** [comment]
这个 dts 的机制是这样子的，但是实际代码中没用到的不会引入，这个放心

**Comment by wc19950724** [comment]
> 这个 dts 的机制是这样子的，但是实际代码中没用到的不会引入，这个放心

好嘞，感谢解答！
