### ISSUE TITLE
`components.d.ts` cannot work with Nuxt3

### ISSUE THREAD

**Issue by kaikaibenkai** [antfu/unplugin-vue-components#657]
### Describe the bug

If enable `unplugin-vue-components`, the types of components that are auto-imported by Nuxt is lost.

### Reproduction

https://github.com/kaikaibenkai/unplugin-vue-components-demo-657

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 1.42 GB / 7.23 GB
  Binaries:
    Node: 18.15.0 - C:\nodejs\node.EXE
    Yarn: 1.22.19 - C:\nodejs\yarn.CMD
    npm: 9.6.4 - C:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.79)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ojvribeiro** [comment]
Is there a reason why you would want to use this plugin in Nuxt?

**Comment by kaikaibenkai** [comment]
> Is there a reason why you would want to use this plugin in Nuxt?

Because auto-import of Arco Design only supports this plugin, if I use Nuxt auto-import, I must fully import Arco Design, causing the package volume to expand.

**Comment by lishaobos** [comment]
hi, you can try:

1. patch the nuxt.config.ts

```ts
export default defineNuxtConfig({
  ssr: false,
  components: false,
  vite: {
    plugins: [
      Components({
        dts: true,
        dirs: ['components'],
        directoryAsNamespace: true,
        resolvers: [
          ArcoResolver({ resolveIcons: true }),
        ],
      }),
    ],
  },
});
```

2. patch the tsconfig.json

```json
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "include": [
    "./.nuxt/nuxt.d.ts",
    "**/*"
  ]
}

```
