### ISSUE TITLE
（vue2.7）当将element-ui中的table与pagination进行二次封装时，table不出来

### ISSUE THREAD

**Issue by SeaWaveW** [antfu/unplugin-vue-components#676]
### Describe the bug

这是封装的代码块 ↓
![image](https://github.com/antfu/unplugin-vue-components/assets/59683106/4f901aad-91b9-4082-beaf-ce11c0312dcc)
但实际上是pagination显示，其中的table不显示
![image](https://github.com/antfu/unplugin-vue-components/assets/59683106/80350666-0d0c-4c30-adcd-e800abd3790f)

### Reproduction

https://github.com/SeaWaveW/issuse.git

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-8100T CPU @ 3.10GHz
    Memory: 1.47 GB / 7.83 GB
  Binaries:
    Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by leedawn** [comment]
本地跑了一下，是有 el-table 的。
![image](https://github.com/antfu/unplugin-vue-components/assets/11451499/92cf85d4-6461-438d-b826-f10f57ac9805)

**Comment by SeaWaveW** [comment]
> 本地跑了一下，是有 el-table 的。 ![image](https://user-images.githubusercontent.com/11451499/260008577-92cf85d4-6461-438d-b826-f10f57ac9805.png)

收到启发，原来问题出在ref上，不能定义与组件name同样的ref。 铁汁🐮🍺

**Comment by shihongxins** [comment]
@SeaWaveW 老哥，你出现过开发没问题，打包之后部分 element-ui 的组件没生效（比如 el-input 或者 el-select 不渲染）的问题吗？
> 示例仓库：https://github.com/shihongxins/vite-vue2-element-ui

> 截图：
>>开发时
![dev](https://raw.githubusercontent.com/shihongxins/vite-vue2-element-ui/main/dev.png)

>>打包后
![dev](https://raw.githubusercontent.com/shihongxins/vite-vue2-element-ui/main/buildThenPreview.png)
